// apps/admin-svelte/src/lib/Invoice.svelte
<script lang="ts" module>
  export type InvoiceStatus = 'paid' | 'unpaid' | 'overdue' | 'draft';
  export interface InvoiceLine {
    id?: string;
    title: string;
    description?: string;
    quantity?: number;
    unitPrice?: number;
    /** The whole row's figure, when it is not quantity × unit price. */
    amount?: number;
  }
  export interface InvoiceStep {
    label: string;
    /** A share of the subtotal (0.09 = 9% tax); `amount` wins when both are given. */
    percent?: number;
    amount?: number;
  }
  export interface InvoiceParty {
    name: string;
    /** Address, email, tax id — a line each. */
    lines?: string[];
  }

  /** The badge speaks in job statuses; an invoice maps onto them. */
  export const BADGE_OF: Record<InvoiceStatus, 'success' | 'queued' | 'failed' | 'canceled'> = { paid: 'success', unpaid: 'queued', overdue: 'failed', draft: 'canceled' };
</script>

<script lang="ts">
  /**
   * The invoice block — the hand-written Svelte shape of `nx-invoice`: a
   * printable document — brand head, parties, line items that reveal one row at
   * a time, totals whose digits roll (RollNumber), and the payment state on a
   * status badge. Amounts are pure props (quantity × unit price unless you give
   * `amount`); the words the document says come from the core i18n table.
   */
  import { onMount } from 'svelte';
  import { type Cleanup, reveal, translate } from '@nabuxai/ui-core';
  import { app, intlLocale } from '../store.svelte';
  import RollNumber from './RollNumber.svelte';

  let {
    brand,
    brandTagline = undefined,
    brandMark = undefined,
    number,
    issueDate = undefined,
    dueDate = undefined,
    status = undefined,
    statusLabel = undefined,
    from,
    to,
    lines,
    extraTotals = [],
    currency = undefined,
    decimals = 0,
    note = undefined,
    footer = undefined,
    caption = undefined,
  }: {
    brand: string;
    brandTagline?: string;
    brandMark?: string;
    number: string;
    issueDate?: string;
    dueDate?: string;
    status?: InvoiceStatus;
    statusLabel?: string;
    from: InvoiceParty;
    to: InvoiceParty;
    lines: InvoiceLine[];
    extraTotals?: InvoiceStep[];
    /** The unit shown beside every figure: "$", "تومان"… */
    currency?: string;
    decimals?: number;
    note?: string;
    footer?: string;
    /** The payment caption on the foot (the core's own word by default). */
    caption?: string;
  } = $props();

  let root: HTMLElement;
  let body: HTMLTableSectionElement;
  let stopRoot: Cleanup | null = null;
  let stopBody: Cleanup | null = null;

  const intl = $derived(intlLocale());
  const format = $derived({ minimumFractionDigits: decimals, maximumFractionDigits: decimals } as Intl.NumberFormatOptions);
  const word = (key: 'invoiceTitle' | 'invoiceNumber' | 'invoiceIssueDate' | 'invoiceDueDate' | 'invoiceFrom' | 'invoiceTo' | 'invoiceItem' | 'invoiceQuantity' | 'invoiceUnitPrice' | 'invoiceAmount' | 'invoiceSubtotal' | 'invoiceTotal' | 'invoicePaid' | 'invoiceUnpaid' | 'invoiceOverdue' | 'invoiceDraft' | 'invoiceCaption') => translate(app.lang, key);

  const rows = $derived(
    lines.map((line, i) => ({
      key: line.id ?? String(i),
      line,
      sum: line.amount ?? (line.quantity ?? 1) * (line.unitPrice ?? 0),
    })),
  );
  const subtotal = $derived(rows.reduce((sum, row) => sum + row.sum, 0));
  const steps = $derived(extraTotals.map((step) => ({ step, amount: step.amount ?? subtotal * (step.percent ?? 0) })));
  const total = $derived(steps.reduce((sum, step) => sum + step.amount, subtotal));

  const statusWord = $derived(status ? { paid: word('invoicePaid'), unpaid: word('invoiceUnpaid'), overdue: word('invoiceOverdue'), draft: word('invoiceDraft') }[status] : '');
  const badge = $derived(status ? BADGE_OF[status] : undefined);

  // The sections rise one after another; the line items one row at a time.
  onMount(() => {
    stopRoot = reveal(root, { stagger: true });
    stopBody = reveal(body, { stagger: true });
    return () => {
      stopRoot?.();
      stopBody?.();
    };
  });
</script>

<article bind:this={root} class="nx-invoice" data-status={status} data-nx-reveal="group" aria-labelledby="nx-invoice-title">
  <header class="nx-invoice-section nx-invoice-head">
    <div class="nx-invoice-brand">
      <div class="nx-invoice-brand-row">
        <span class="nx-invoice-mark" aria-hidden={brandMark ? undefined : 'true'}>{brandMark ?? Array.from(brand)[0]}</span>
        <span class="nx-invoice-brand-name">{brand}</span>
      </div>
      {#if brandTagline}<span class="nx-invoice-brand-tagline">{brandTagline}</span>{/if}
    </div>
    <div class="nx-invoice-meta">
      <h2 class="nx-invoice-title" id="nx-invoice-title">{word('invoiceTitle')}</h2>
      <dl class="nx-invoice-facts">
        <div>
          <dt>{word('invoiceNumber')}</dt>
          <dd>{number}</dd>
        </div>
        {#if issueDate}
          <div>
            <dt>{word('invoiceIssueDate')}</dt>
            <dd>{issueDate}</dd>
          </div>
        {/if}
        {#if dueDate}
          <div>
            <dt>{word('invoiceDueDate')}</dt>
            <dd>{dueDate}</dd>
          </div>
        {/if}
      </dl>
      {#if status && badge}
        {@const label = statusLabel ?? statusWord}
        <span class="nx-status-badge" data-status={badge}>
          <span class="nx-visually-hidden">{label}</span>
          <span class="nx-status-badge-layers" aria-hidden="true">
            <span class="nx-status-badge-layer" data-for={badge}>
              {#if badge === 'success' || badge === 'canceled'}
                <span class="nx-status-badge-icon">
                  <svg viewBox="0 0 16 16">
                    <circle class="nx-status-badge-disc" cx="8" cy="8" r="7.5"></circle>
                    <path class="nx-status-badge-mark" d={badge === 'success' ? 'M4.9 8.3l2.1 2.1 4.1-4.4' : 'M5.7 5.7l4.6 4.6M10.3 5.7l-4.6 4.6'} pathLength="1"></path>
                  </svg>
                </span>
              {:else if badge === 'failed'}
                <span class="nx-status-badge-icon">
                  <svg viewBox="0 0 16 16">
                    <circle cx="8" cy="8" r="6.25"></circle>
                    <path class="nx-status-badge-mark" d="M3.8 12.2L12.2 3.8" pathLength="1"></path>
                  </svg>
                </span>
              {:else if badge === 'queued'}
                <span class="nx-status-badge-icon">
                  <span class="nx-status-badge-dots">
                    <i></i>
                    <i></i>
                    <i></i>
                  </span>
                </span>
              {/if}
              <span class="nx-status-badge-label">{label}</span>
            </span>
          </span>
        </span>
      {/if}
    </div>
  </header>

  <div class="nx-invoice-section nx-invoice-parties">
    {#each [{ kind: 'from', party: from, partyLabel: word('invoiceFrom') }, { kind: 'to', party: to, partyLabel: word('invoiceTo') }] as group (group.kind)}
      <div class="nx-invoice-party" data-kind={group.kind}>
        <span class="nx-invoice-party-label">{group.partyLabel}</span>
        <p class="nx-invoice-party-name">{group.party.name}</p>
        {#if group.party.lines && group.party.lines.length > 0}
          <div class="nx-invoice-party-lines">
            {#each group.party.lines as line, i (i)}
              <span>{line}</span>
            {/each}
          </div>
        {/if}
      </div>
    {/each}
  </div>

  <table class="nx-invoice-section nx-invoice-lines">
    <caption class="nx-visually-hidden">{word('invoiceTitle')} {number}</caption>
    <thead>
      <tr>
        <th scope="col" class="nx-invoice-index-head" aria-label="#"></th>
        <th scope="col">{word('invoiceItem')}</th>
        <th scope="col" data-align="end">{word('invoiceQuantity')}</th>
        <th scope="col" data-align="end">{word('invoiceUnitPrice')}</th>
        <th scope="col" data-align="end">{word('invoiceAmount')}</th>
      </tr>
    </thead>
    <tbody bind:this={body} data-nx-reveal="group">
      {#each rows as row, i (row.key)}
        <tr class="nx-invoice-line" style:--nx-i={i}>
          <td class="nx-invoice-index">{new Intl.NumberFormat(intl).format(i + 1)}</td>
          <td class="nx-invoice-item">
            <span class="nx-invoice-item-title">{row.line.title}</span>
            {#if row.line.description}<span class="nx-invoice-item-description">{row.line.description}</span>{/if}
          </td>
          <td data-align="end">{row.line.quantity !== undefined ? new Intl.NumberFormat(intl).format(row.line.quantity) : '—'}</td>
          <td data-align="end">{row.line.unitPrice !== undefined ? new Intl.NumberFormat(intl, format).format(row.line.unitPrice) : '—'}</td>
          <td data-align="end">
            <span class="nx-invoice-amount">
              <RollNumber value={row.sum} {format} roll={false} />
              {#if currency}<span class="nx-invoice-currency">{currency}</span>{/if}
            </span>
          </td>
        </tr>
      {/each}
    </tbody>
  </table>

  <div class="nx-invoice-section nx-invoice-totals">
    <div class="nx-invoice-row">
      <span>{word('invoiceSubtotal')}</span>
      <span class="nx-invoice-amount">
        <RollNumber value={subtotal} {format} />
        {#if currency}<span class="nx-invoice-currency">{currency}</span>{/if}
      </span>
    </div>
    {#each steps as step, i (i)}
      <div class="nx-invoice-row">
        <span>{step.step.label}</span>
        <span class="nx-invoice-amount">
          <RollNumber value={step.amount} {format} />
          {#if currency}<span class="nx-invoice-currency">{currency}</span>{/if}
        </span>
      </div>
    {/each}
    <div class="nx-invoice-total">
      <span class="nx-invoice-total-label">{word('invoiceTotal')}</span>
      <span class="nx-invoice-amount">
        <RollNumber value={total} {format} />
        {#if currency}<span class="nx-invoice-currency">{currency}</span>{/if}
      </span>
    </div>
    {#if note}<p class="nx-invoice-note">{note}</p>{/if}
  </div>

  <footer class="nx-invoice-section nx-invoice-foot">
    <span>{footer ?? caption ?? word('invoiceCaption')}</span>
    <span>{brand}</span>
  </footer>
</article>

// packages/react/src/blocks/invoice.tsx
/**
 * The invoice block (React): a printable document — brand head, parties,
 * line items that reveal one row at a time, totals whose digits roll
 * (css/blocks/invoice.css), and the payment state on a StatusBadge.
 * Amounts are pure props (quantity × unit price unless you give `amount`);
 * there is nothing to fetch.
 */
import {
  type CSSProperties,
  type HTMLAttributes,
  type ReactNode,
  useId,
  useMemo,
  useRef,
} from 'react';
import type { MessageKey } from '@nabuxai/ui-core';
import { cx } from '../internal/hooks';
import { useLocale, useT } from '../internal/provider';
import { NumberTicker, useReveal } from '../components/text';
import { StatusBadge, type JobStatus } from './data';

const INTL = { en: 'en-US', fa: 'fa-IR', ar: 'ar' } as const;
const vars = (style: Record<string, string | number | undefined>) => style as CSSProperties;

export type InvoiceStatus = 'paid' | 'unpaid' | 'overdue' | 'draft';

/** The badge speaks in job statuses; an invoice maps onto them. */
const BADGE_OF: Record<InvoiceStatus, JobStatus> = { paid: 'success', unpaid: 'queued', overdue: 'failed', draft: 'canceled' };

/** The words the invoice says itself; override any of them with `labels`. */
type InvoiceWord =
  | 'title' | 'number' | 'issueDate' | 'dueDate' | 'from' | 'to'
  | 'item' | 'quantity' | 'unitPrice' | 'amount' | 'subtotal' | 'total'
  | 'paid' | 'unpaid' | 'overdue' | 'draft' | 'caption';

/** Where each of them lives in the core i18n table. */
const WORD_KEYS: Record<InvoiceWord, MessageKey> = {
  title: 'invoiceTitle',
  number: 'invoiceNumber',
  issueDate: 'invoiceIssueDate',
  dueDate: 'invoiceDueDate',
  from: 'invoiceFrom',
  to: 'invoiceTo',
  item: 'invoiceItem',
  quantity: 'invoiceQuantity',
  unitPrice: 'invoiceUnitPrice',
  amount: 'invoiceAmount',
  subtotal: 'invoiceSubtotal',
  total: 'invoiceTotal',
  paid: 'invoicePaid',
  unpaid: 'invoiceUnpaid',
  overdue: 'invoiceOverdue',
  draft: 'invoiceDraft',
  caption: 'invoiceCaption',
};

export interface InvoiceLine {
  /** Keeps its DOM node across re-renders; the index by default. */
  id?: string;
  title: ReactNode;
  description?: ReactNode;
  quantity?: number;
  unitPrice?: number;
  /** The whole row's figure, when it is not quantity × unit price. */
  amount?: number;
}

export interface InvoiceStep {
  label: ReactNode;
  /** A share of the subtotal (0.09 = 9% tax); `amount` wins when both are given. */
  percent?: number;
  amount?: number;
}

export interface InvoiceParty {
  name: ReactNode;
  /** Address, email, tax id — a line each. */
  lines?: ReactNode[];
}

export interface InvoiceProps extends Omit<HTMLAttributes<HTMLElement>, 'children'> {
  brand: ReactNode;
  brandTagline?: ReactNode;
  /** The square mark; the brand's first letter by default. */
  brandMark?: ReactNode;
  number: ReactNode;
  issueDate?: ReactNode;
  dueDate?: ReactNode;
  status?: InvoiceStatus;
  statusLabel?: string;
  from: InvoiceParty;
  to: InvoiceParty;
  lines: InvoiceLine[];
  /** Steps between the subtotal and the total (tax, discount — a negative amount). */
  extraTotals?: InvoiceStep[];
  /** The unit shown beside every figure: "$", "تومان", "USD"… */
  currency?: ReactNode;
  /** Fraction digits (0 for tomans, 2 for dollars). */
  decimals?: number;
  note?: ReactNode;
  footer?: ReactNode;
  labels?: Partial<Record<InvoiceWord, string>>;
  locale?: string;
}

export function Invoice({
  brand,
  brandTagline,
  brandMark,
  number,
  issueDate,
  dueDate,
  status,
  statusLabel,
  from,
  to,
  lines,
  extraTotals = [],
  currency,
  decimals = 0,
  note,
  footer,
  labels,
  locale,
  className,
  ...rest
}: InvoiceProps) {
  const t = useT();
  const language = useLocale();
  const intl = locale ?? INTL[language];
  // `labels` may override any word; the rest come from the core table.
  const word = (key: InvoiceWord) => labels?.[key] ?? t(WORD_KEYS[key]);
  const id = useId();
  const root = useRef<HTMLElement>(null);
  const body = useRef<HTMLTableSectionElement>(null);
  // The sections rise one after another; the line items one row at a time.
  useReveal(root, { stagger: true });
  useReveal(body, { stagger: true });

  const format = useMemo(
    () => ({ minimumFractionDigits: decimals, maximumFractionDigits: decimals }) as Intl.NumberFormatOptions,
    [decimals],
  );

  const rows = useMemo(
    () =>
      lines.map((line, i) => ({
        key: line.id ?? String(i),
        line,
        sum: line.amount ?? (line.quantity ?? 1) * (line.unitPrice ?? 0),
      })),
    [lines],
  );
  const subtotal = useMemo(() => rows.reduce((sum, row) => sum + row.sum, 0), [rows]);
  const steps = useMemo(
    () => extraTotals.map((step) => ({ step, amount: step.amount ?? subtotal * (step.percent ?? 0) })),
    [extraTotals, subtotal],
  );
  const total = useMemo(() => steps.reduce((sum, step) => sum + step.amount, subtotal), [steps, subtotal]);

  /** The totals roll their digits; line amounts ride their row's reveal instead. */
  const money = (value: number, roll = true) => (
    <span className="nx-invoice-amount">
      <NumberTicker value={value} locale={intl} format={format} reveal={roll} />
      {currency && <span className="nx-invoice-currency">{currency}</span>}
    </span>
  );

  const facts: Array<[label: string, value: ReactNode] | null> = [
    [word('number'), number],
    issueDate ? [word('issueDate'), issueDate] : null,
    dueDate ? [word('dueDate'), dueDate] : null,
  ];

  return (
    <article ref={root} className={cx('nx-invoice', className)} data-status={status} data-nx-reveal="group" aria-labelledby={`${id}-title`} {...rest}>
      <header className="nx-invoice-section nx-invoice-head">
        <div className="nx-invoice-brand">
          <div className="nx-invoice-brand-row">
            <span className="nx-invoice-mark" aria-hidden={brandMark ? undefined : true}>
              {brandMark ?? (typeof brand === 'string' ? Array.from(brand)[0] : 'N')}
            </span>
            <span className="nx-invoice-brand-name">{brand}</span>
          </div>
          {brandTagline && <span className="nx-invoice-brand-tagline">{brandTagline}</span>}
        </div>
        <div className="nx-invoice-meta">
          <h2 className="nx-invoice-title" id={`${id}-title`}>
            {word('title')}
          </h2>
          {facts.some(Boolean) && (
            <dl className="nx-invoice-facts">
              {facts.map((fact) =>
                fact ? (
                  <div key={String(fact[0])}>
                    <dt>{fact[0]}</dt>
                    <dd>{fact[1]}</dd>
                  </div>
                ) : null,
              )}
            </dl>
          )}
          {status && (
            <StatusBadge
              status={BADGE_OF[status]}
              label={statusLabel}
              labels={{ success: word('paid'), queued: word('unpaid'), failed: word('overdue'), canceled: word('draft') }}
            />
          )}
        </div>
      </header>

      <div className="nx-invoice-section nx-invoice-parties">
        {([['from', from, word('from')], ['to', to, word('to')]] as const).map(([kind, party, label]) => (
          <div key={kind} className="nx-invoice-party" data-kind={kind}>
            <span className="nx-invoice-party-label">{label}</span>
            <p className="nx-invoice-party-name">{party.name}</p>
            {party.lines && party.lines.length > 0 && (
              <div className="nx-invoice-party-lines">
                {party.lines.map((line, i) => (
                  <span key={i}>{line}</span>
                ))}
              </div>
            )}
          </div>
        ))}
      </div>

      <table className="nx-invoice-section nx-invoice-lines">
        <caption className="nx-visually-hidden">
          {word('title')} {number}
        </caption>
        <thead>
          <tr>
            <th scope="col" className="nx-invoice-index-head" aria-label="#" />
            <th scope="col">{word('item')}</th>
            <th scope="col" data-align="end">
              {word('quantity')}
            </th>
            <th scope="col" data-align="end">
              {word('unitPrice')}
            </th>
            <th scope="col" data-align="end">
              {word('amount')}
            </th>
          </tr>
        </thead>
        <tbody ref={body} data-nx-reveal="group">
          {rows.map((row, i) => (
            <tr key={row.key} className="nx-invoice-line" style={vars({ '--nx-i': i })}>
              <td className="nx-invoice-index">{new Intl.NumberFormat(intl).format(i + 1)}</td>
              <td className="nx-invoice-item">
                <span className="nx-invoice-item-title">{row.line.title}</span>
                {row.line.description && <span className="nx-invoice-item-description">{row.line.description}</span>}
              </td>
              <td data-align="end">{row.line.quantity !== undefined ? new Intl.NumberFormat(intl).format(row.line.quantity) : '—'}</td>
              <td data-align="end">{row.line.unitPrice !== undefined ? new Intl.NumberFormat(intl, format).format(row.line.unitPrice) : '—'}</td>
              <td data-align="end">{money(row.sum, false)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="nx-invoice-section nx-invoice-totals">
        <div className="nx-invoice-row">
          <span>{word('subtotal')}</span>
          {money(subtotal)}
        </div>
        {steps.map((step, i) => (
          <div key={i} className="nx-invoice-row">
            <span>{step.step.label}</span>
            {money(step.amount)}
          </div>
        ))}
        <div className="nx-invoice-total">
          <span className="nx-invoice-total-label">{word('total')}</span>
          {money(total)}
        </div>
        {note && <p className="nx-invoice-note">{note}</p>}
      </div>

      <footer className="nx-invoice-section nx-invoice-foot">
        <span>{footer ?? word('caption')}</span>
        <span>{brand}</span>
      </footer>
    </article>
  );
}
