// apps/admin/src/pages/settings.tsx
/**
 * /#/settings — store configuration and the user's own preferences. The
 * ThemeSwitch writes the shared core theme store by itself; the LanguageMenu
 * persists the app's saved pick (`nabuxai.admin.lang`, the key lang.tsx
 * reads at mount) and reloads so the whole panel — shell included — lands in
 * the new language; the hash survives the reload, so this page stays put.
 * The danger zone asks for the delete word before its button wakes up, and
 * "deleting" the demo store simply ends the session at the sign-in view.
 */
import { useState, type FormEvent } from 'react';
import {
  Button,
  Card,
  Dialog,
  Field,
  Input,
  LanguageMenu,
  Select,
  Switch,
  ThemeSwitch,
  toast,
  type ButtonStatus,
} from '@nabuxai/ui-react';
import { useLang, useStrings } from '../lang';
import { useRoute } from '../router';

export function SettingsPage() {
  const s = useStrings();
  const set = s.pages.settings;
  const lang = useLang();
  const [, go] = useRoute();

  const [saveState, setSaveState] = useState<ButtonStatus>('idle');
  const [twoFactor, setTwoFactor] = useState(true);
  const [digest, setDigest] = useState(true);
  const [push, setPush] = useState(false);
  const [weekly, setWeekly] = useState(true);
  const [passwordOpen, setPasswordOpen] = useState(false);
  const [confirm, setConfirm] = useState('');
  const deleteWord = set.deleteWord;
  const armed = confirm.trim().toLowerCase() === deleteWord;

  const saveGeneral = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (saveState !== 'idle') return;
    setSaveState('loading');
    window.setTimeout(() => {
      setSaveState('success');
      toast.success(s.common.saved);
      window.setTimeout(() => setSaveState('idle'), 1400);
    }, 700);
  };

  // The panel's language lives in App state; the one bridge a page has is the
  // saved pick in localStorage + a reload — the same key readLang() reads.
  const changeLang = (id: string) => {
    try {
      localStorage.setItem('nabuxai.admin.lang', id === 'en' ? 'en' : 'fa');
    } catch {
      /* storage closed: the menu rolls back below */
    }
    window.location.reload();
  };

  const signOutEverywhere = () => toast.info(set.signedOutEverywhere);

  const deleteStore = () => {
    go('login');
    toast.warning(set.storeDeleted);
  };

  return (
    <div className="adm-settings">
      <Card className="adm-settings-general" title={set.general} titleAs="h2" icon="settings">
        <form className="adm-form" onSubmit={saveGeneral}>
          <div className="adm-form-grid">
            <Field label={set.workspaceName}>
              <Input name="workspace" defaultValue={s.app.storeName} required />
            </Field>
            <Field label={set.workspaceUrl}>
              <Input name="url" dir="ltr" defaultValue="nabu.shop" startAddon="https://" />
            </Field>
            <Field label={set.timezoneField} className="adm-form-span">
              <Select
                name="timezone"
                defaultValue="Asia/Tehran"
                options={[
                  { value: 'Asia/Tehran', label: s.common.tzTehran },
                  { value: 'Europe/Berlin', label: s.common.tzBerlin },
                  { value: 'UTC', label: 'UTC' },
                ]}
              />
            </Field>
          </div>
          <div className="adm-form-actions">
            <Button type="submit" variant="primary" icon="check" status={saveState}>{s.common.save}</Button>
          </div>
        </form>
      </Card>

      <Card title={set.appearance} titleAs="h2" icon="sun">
        <div className="adm-row">
          <span className="adm-row-text">
            <span className="adm-row-label">{set.theme}</span>
            <span className="adm-row-hint">{set.themeHint}</span>
          </span>
          <ThemeSwitch label={set.theme} />
        </div>
      </Card>

      <Card title={set.languageSection} titleAs="h2" icon="globe">
        <div className="adm-row">
          <span className="adm-row-text">
            <span className="adm-row-label">{set.languageFa} · {set.languageEn}</span>
            <span className="adm-row-hint">{set.languageHint}</span>
          </span>
          <LanguageMenu
            label={set.languageSection}
            value={lang}
            onValueChange={changeLang}
            languages={[
              { id: 'fa', name: set.languageFa, short: 'FA' },
              { id: 'en', name: set.languageEn, short: 'EN' },
            ]}
          />
        </div>
      </Card>

      <Card title={set.notifications} titleAs="h2" icon="bell">
        <div className="adm-choices">
          <Switch label={set.emailDigest} checked={digest} onCheckedChange={setDigest} />
          <Switch label={set.pushAlerts} checked={push} onCheckedChange={setPush} />
          <Switch label={set.weeklyReport} checked={weekly} onCheckedChange={setWeekly} />
        </div>
      </Card>

      <Card title={set.security} titleAs="h2" icon="lock">
        <div className="adm-choices">
          <Switch label={set.twoFactor} checked={twoFactor} onCheckedChange={setTwoFactor} />
          <div className="adm-row">
            <span className="adm-row-text">
              <span className="adm-row-label">{set.password}</span>
            </span>
            <Dialog
              open={passwordOpen}
              onOpenChange={setPasswordOpen}
              trigger={<Button size="sm" variant="outline" icon="lock">{s.common.edit}</Button>}
              title={set.password}
              description={set.passwordDescription}
              footer={
                <>
                  <Button variant="ghost" onClick={() => setPasswordOpen(false)}>{s.common.cancel}</Button>
                  <Button
                    variant="primary"
                    icon="check"
                    onClick={() => {
                      setPasswordOpen(false);
                      toast.success(set.passwordUpdated);
                    }}
                  >
                    {s.common.confirm}
                  </Button>
                </>
              }
            >
              <Field label={s.common.currentPassword}>
                <Input type="password" dir="ltr" autoComplete="current-password" required />
              </Field>
              <Field label={s.common.newPassword}>
                <Input type="password" dir="ltr" autoComplete="new-password" required minLength={8} />
              </Field>
            </Dialog>
          </div>
          <div className="adm-row">
            <span className="adm-row-text">
              <span className="adm-row-label">{set.signOutDevices}</span>
            </span>
            <Button size="sm" variant="outline" icon="lock" onClick={signOutEverywhere}>{s.common.confirm}</Button>
          </div>
        </div>
      </Card>

      <Card className="adm-settings-danger" title={set.danger} titleAs="h2" icon="alert-triangle" description={set.deleteBody}>
        <div className="adm-danger">
          <Field label={set.typeToDelete} hint={set.confirmWord}>
            <Input value={confirm} onChange={(event) => setConfirm(event.target.value)} dir="ltr" autoComplete="off" placeholder={deleteWord} />
          </Field>
          <Button variant="danger" icon="trash" disabled={!armed} onClick={deleteStore}>
            {set.deleteWorkspace}
          </Button>
        </div>
      </Card>
    </div>
  );
}

// apps/admin-vue/src/pages/settings.vue
<script setup lang="ts">
/**
 * Settings — store configuration and the user's own preferences. The
 * ThemeSwitch writes the shared core theme store; the language menu calls
 * `setLang`, which flips the whole panel — shell included — on the spot (no
 * reload needed in this flavour). The danger zone asks for the delete word
 * before its button wakes up, and "deleting" the demo store simply ends the
 * session at the sign-in view.
 */
import { computed, nextTick, ref, watch } from 'vue';
import { toast } from '@nabuxai/ui-core';
import { s } from '../store';
import { go } from '../router';
import NxIcon from '../components/NxIcon.vue';
import ThemeSwitch from '../components/ThemeSwitch.vue';
import LangMenu from '../components/LangMenu.vue';

const set = computed(() => s.value.pages.settings);

type ButtonStatus = 'idle' | 'loading' | 'success';

const saveState = ref<ButtonStatus>('idle');
const twoFactor = ref(true);
const digest = ref(true);
const push = ref(false);
const weekly = ref(true);
const passwordOpen = ref(false);
const confirm = ref('');
const passwordDialog = ref<HTMLDialogElement | null>(null);

const armed = computed(() => confirm.value.trim().toLowerCase() === set.value.deleteWord);

const saveGeneral = (event: Event) => {
  event.preventDefault();
  if (saveState.value !== 'idle') return;
  saveState.value = 'loading';
  window.setTimeout(() => {
    saveState.value = 'success';
    toast.success(s.value.common.saved);
    window.setTimeout(() => (saveState.value = 'idle'), 1400);
  }, 700);
};

watch(passwordOpen, (open) => void nextTick(() => (open ? passwordDialog.value?.showModal() : passwordDialog.value?.close())));
const closePassword = () => (passwordOpen.value = false);

const updatePassword = () => {
  passwordOpen.value = false;
  toast.success(set.value.passwordUpdated);
};

const signOutEverywhere = () => toast.info(set.value.signedOutEverywhere);

const deleteStore = () => {
  go('login');
  toast.warning(set.value.storeDeleted);
};

const languageOptions = computed(() => [
  { id: 'fa' as const, name: set.value.languageFa, short: 'FA' },
  { id: 'en' as const, name: set.value.languageEn, short: 'EN' },
]);
</script>

<template>
  <div class="adm-settings">
    <section class="nx-card adm-settings-general">
      <div class="nx-card-header">
        <span class="nx-card-icon"><NxIcon name="settings" /></span>
        <h2 class="nx-card-title">{{ set.general }}</h2>
      </div>
      <div class="nx-card-body">
        <form class="adm-form" @submit="saveGeneral">
          <div class="adm-form-grid">
            <div class="nx-field">
              <label class="nx-label" for="settings-name">{{ set.workspaceName }}</label>
              <input id="settings-name" name="workspace" class="nx-input" :value="s.app.storeName" required />
            </div>
            <div class="nx-field">
              <label class="nx-label" for="settings-url">{{ set.workspaceUrl }}</label>
              <div class="nx-input-group">
                <span class="nx-input-addon">https://</span>
                <input id="settings-url" name="url" class="nx-input" dir="ltr" value="nabu.shop" />
              </div>
            </div>
            <div class="nx-field adm-form-span">
              <label class="nx-label" for="settings-tz">{{ set.timezoneField }}</label>
              <select id="settings-tz" name="timezone" class="nx-select">
                <option value="Asia/Tehran">{{ s.common.tzTehran }}</option>
                <option value="Europe/Berlin">{{ s.common.tzBerlin }}</option>
                <option value="UTC">UTC</option>
              </select>
            </div>
          </div>
          <div class="adm-form-actions">
            <button type="submit" class="nx-button" data-variant="primary" :data-status="saveState === 'idle' ? undefined : saveState">
              <span class="nx-button-label">
                <NxIcon name="check" />
                <span class="nx-button-text">{{ s.common.save }}</span>
                <span v-if="saveState !== 'idle'" class="nx-button-status" aria-hidden="true">
                  <span class="nx-spinner" data-size="sm" />
                  <svg class="nx-icon nx-status-check" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M5 12.5l4.5 4.5L19 7.5" pathLength="1" />
                  </svg>
                </span>
              </span>
            </button>
          </div>
        </form>
      </div>
    </section>

    <section class="nx-card">
      <div class="nx-card-header">
        <span class="nx-card-icon"><NxIcon name="sun" /></span>
        <h2 class="nx-card-title">{{ set.appearance }}</h2>
      </div>
      <div class="nx-card-body">
        <div class="adm-row">
          <span class="adm-row-text">
            <span class="adm-row-label">{{ set.theme }}</span>
            <span class="adm-row-hint">{{ set.themeHint }}</span>
          </span>
          <ThemeSwitch :label="set.theme" />
        </div>
      </div>
    </section>

    <section class="nx-card">
      <div class="nx-card-header">
        <span class="nx-card-icon"><NxIcon name="globe" /></span>
        <h2 class="nx-card-title">{{ set.languageSection }}</h2>
      </div>
      <div class="nx-card-body">
        <div class="adm-row">
          <span class="adm-row-text">
            <span class="adm-row-label">{{ set.languageFa }} · {{ set.languageEn }}</span>
            <span class="adm-row-hint">{{ set.languageHint }}</span>
          </span>
          <LangMenu :label="set.languageSection" :options="languageOptions" />
        </div>
      </div>
    </section>

    <section class="nx-card">
      <div class="nx-card-header">
        <span class="nx-card-icon"><NxIcon name="bell" /></span>
        <h2 class="nx-card-title">{{ set.notifications }}</h2>
      </div>
      <div class="nx-card-body">
        <div class="adm-choices">
          <label class="nx-choice">
            <input v-model="digest" class="nx-switch" type="checkbox" role="switch" />
            <span class="nx-choice-text"><span class="nx-choice-label">{{ set.emailDigest }}</span></span>
          </label>
          <label class="nx-choice">
            <input v-model="push" class="nx-switch" type="checkbox" role="switch" />
            <span class="nx-choice-text"><span class="nx-choice-label">{{ set.pushAlerts }}</span></span>
          </label>
          <label class="nx-choice">
            <input v-model="weekly" class="nx-switch" type="checkbox" role="switch" />
            <span class="nx-choice-text"><span class="nx-choice-label">{{ set.weeklyReport }}</span></span>
          </label>
        </div>
      </div>
    </section>

    <section class="nx-card">
      <div class="nx-card-header">
        <span class="nx-card-icon"><NxIcon name="lock" /></span>
        <h2 class="nx-card-title">{{ set.security }}</h2>
      </div>
      <div class="nx-card-body">
        <div class="adm-choices">
          <label class="nx-choice">
            <input v-model="twoFactor" class="nx-switch" type="checkbox" role="switch" />
            <span class="nx-choice-text"><span class="nx-choice-label">{{ set.twoFactor }}</span></span>
          </label>
          <div class="adm-row">
            <span class="adm-row-text"><span class="adm-row-label">{{ set.password }}</span></span>
            <button type="button" class="nx-button" data-variant="outline" data-size="sm" @click="passwordOpen = true">
              <span class="nx-button-label">
                <NxIcon name="lock" />
                <span class="nx-button-text">{{ s.common.edit }}</span>
              </span>
            </button>
          </div>
          <div class="adm-row">
            <span class="adm-row-text"><span class="adm-row-label">{{ set.signOutDevices }}</span></span>
            <button type="button" class="nx-button" data-variant="outline" data-size="sm" @click="signOutEverywhere">
              <span class="nx-button-label">
                <NxIcon name="lock" />
                <span class="nx-button-text">{{ s.common.confirm }}</span>
              </span>
            </button>
          </div>
        </div>
      </div>
    </section>

    <section class="nx-card adm-settings-danger">
      <div class="nx-card-header">
        <span class="nx-card-icon"><NxIcon name="alert-triangle" /></span>
        <h2 class="nx-card-title">{{ set.danger }}</h2>
        <p class="nx-card-description">{{ set.deleteBody }}</p>
      </div>
      <div class="nx-card-body">
        <div class="adm-danger">
          <div class="nx-field">
            <label class="nx-label" for="settings-confirm">{{ set.typeToDelete }}</label>
            <input id="settings-confirm" v-model="confirm" class="nx-input" dir="ltr" autocomplete="off" :placeholder="set.deleteWord" />
            <p class="nx-hint">{{ set.confirmWord }}</p>
          </div>
          <button type="button" class="nx-button" data-variant="danger" :disabled="!armed" @click="deleteStore">
            <span class="nx-button-label">
              <NxIcon name="trash" />
              <span class="nx-button-text">{{ set.deleteWorkspace }}</span>
            </span>
          </button>
        </div>
      </div>
    </section>

    <dialog ref="passwordDialog" class="nx-dialog" data-size="sm" @close="closePassword" @click.self="closePassword">
      <header class="nx-dialog-header">
        <h2 class="nx-dialog-title">{{ set.password }}</h2>
        <p class="nx-dialog-description">{{ set.passwordDescription }}</p>
      </header>
      <div class="nx-dialog-body adm-form">
        <div class="nx-field">
          <label class="nx-label" for="password-current">{{ s.common.currentPassword }}</label>
          <input id="password-current" class="nx-input" type="password" dir="ltr" autocomplete="current-password" required />
        </div>
        <div class="nx-field">
          <label class="nx-label" for="password-new">{{ s.common.newPassword }}</label>
          <input id="password-new" class="nx-input" type="password" dir="ltr" autocomplete="new-password" required minlength="8" />
        </div>
      </div>
      <footer class="nx-dialog-footer">
        <button type="button" class="nx-button" data-variant="ghost" @click="closePassword">
          <span class="nx-button-label"><span class="nx-button-text">{{ s.common.cancel }}</span></span>
        </button>
        <button type="button" class="nx-button" data-variant="primary" @click="updatePassword">
          <span class="nx-button-label">
            <NxIcon name="check" />
            <span class="nx-button-text">{{ s.common.confirm }}</span>
          </span>
        </button>
      </footer>
      <button type="button" class="nx-dialog-close" :aria-label="s.common.close" @click="closePassword">
        <NxIcon name="x" />
      </button>
    </dialog>
  </div>
</template>
