// packages/react/src/blocks/chat.tsx
/**
 * The chat block (React): a conversations column (search + unread) beside one
 * message thread — bubbles that pop in, day separators, a growing composer and
 * a three-dot typing indicator (css/blocks/chat.css). State is local/props:
 * sending echoes the message into the thread and tells `onSend`; there is no
 * backend to talk to.
 */
import {
  type CSSProperties,
  type HTMLAttributes,
  type KeyboardEvent,
  type ReactNode,
  Fragment,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
} from 'react';
import { type MessageKey, activityTime, autogrow, foldSearchText, prefersReducedMotion, roveFocus, timeOf } from '@nabuxai/ui-core';
import { cx, useControllable, useIsoLayoutEffect } from '../internal/hooks';
import { Icon } from '../internal/icon';
import { useLocale, useT } from '../internal/provider';
import { Avatar } from '../components/display';
import { useReveal } from '../components/text';

const INTL = { en: 'en-US', fa: 'fa-IR', ar: 'ar' } as const;
const vars = (style: Record<string, string | number | undefined>) => style as CSSProperties;

/** The words the chat says itself; override any of them with the `labels` prop. */
type ChatWord = 'conversations' | 'messages' | 'messagePlaceholder' | 'typing' | 'unread' | 'empty' | 'noMessages';

/** Where each of them lives in the core i18n table. */
const WORD_KEYS: Record<ChatWord, MessageKey> = {
  conversations: 'chatConversations',
  messages: 'chatMessages',
  messagePlaceholder: 'chatMessagePlaceholder',
  typing: 'chatTyping',
  unread: 'chatUnread',
  empty: 'chatEmpty',
  noMessages: 'chatNoMessages',
};

export type ChatPresence = 'online' | 'busy' | 'away' | 'offline';

export interface ChatMessage {
  id: string;
  /** Incoming (them) or outgoing (me); sides mirror themselves in RTL. */
  side: 'in' | 'out';
  text: string;
  /** A Date, timestamp or ISO string; any other string is shown as it is. */
  time?: Date | number | string;
  /** The separator label; derived from `time` in the reader's language when omitted. */
  day?: string;
}

export interface ChatConversation {
  id: string;
  name: string;
  avatar?: string;
  status?: ChatPresence;
  /** Who they are, under the name in the thread header. */
  role?: ReactNode;
  /** The last line, shown in the conversations column. */
  preview?: ReactNode;
  time?: Date | number | string;
  unread?: number;
  /** Show the three-dot indicator in this thread. */
  typing?: boolean;
  messages?: ChatMessage[];
}

export interface ChatProps extends Omit<HTMLAttributes<HTMLElement>, 'children'> {
  conversations: ChatConversation[];
  /** The active conversation's id. */
  value?: string;
  defaultValue?: string;
  onValueChange?: (id: string) => void;
  /** The sent text; the bubble appears locally whatever you do with it. */
  onSend?: (text: string, conversationId: string) => void;
  placeholder?: string;
  searchPlaceholder?: string;
  emptyText?: ReactNode;
  labels?: Partial<Record<ChatWord, string>>;
  /** Height of the whole frame (34rem by default). */
  height?: string;
  locale?: string;
  disabled?: boolean;
}

/** "10:24" for anything that parses as a moment; anything else is shown as it is. */
function clockOf(time: Date | number | string | undefined, locale: string): string | null {
  if (time === undefined) return null;
  const at = timeOf(time);
  return Number.isNaN(at) ? (typeof time === 'string' ? time : null) : new Intl.DateTimeFormat(locale, { hour: 'numeric', minute: '2-digit' }).format(at);
}

/** The day a message belongs to, in the reader's calendar. */
function dayOf(time: Date | number | string | undefined, locale: string): string | null {
  if (time === undefined) return null;
  const at = timeOf(time);
  return Number.isNaN(at) ? null : new Intl.DateTimeFormat(locale, { dateStyle: 'medium' }).format(at);
}

/** The machine-readable moment behind a shown time; undefined when `time` is a plain label. */
function isoOf(time: Date | number | string | undefined): string | undefined {
  if (time === undefined) return undefined;
  const at = timeOf(time);
  return Number.isNaN(at) ? undefined : new Date(at).toISOString();
}

export function Chat({
  conversations,
  value,
  defaultValue,
  onValueChange,
  onSend,
  placeholder,
  searchPlaceholder,
  emptyText,
  labels,
  height,
  locale,
  disabled,
  className,
  style,
  ...rest
}: ChatProps) {
  const t = useT();
  const language = useLocale();
  const intl = locale ?? INTL[language];
  // `labels` may override any word; the rest come from the core table, params filling `{name}` slots.
  const word = (key: ChatWord, params: Record<string, string | number> = {}) => {
    const override = labels?.[key];
    return override === undefined ? t(WORD_KEYS[key], params) : override.replace(/\{(\w+)\}/g, (_, name: string) => String(params[name] ?? ''));
  };

  const base = `nx-chat${useId().replace(/:/g, '')}`;
  const [current, setCurrent] = useControllable(value, defaultValue ?? conversations[0]?.id ?? '', onValueChange);
  const [query, setQuery] = useState('');
  const [draft, setDraft] = useState('');
  const [read, setRead] = useState<Record<string, true>>({});
  const [now, setNow] = useState(() => Date.now());
  const thread = useRef<HTMLDivElement>(null);
  const area = useRef<HTMLTextAreaElement>(null);
  const sequence = useRef(0);
  useReveal(thread, { stagger: true });

  // The thread state starts from (and follows) the conversations prop; messages
  // sent here echo into it. A conversation is keyed by id, its messages by id.
  const signature = useMemo(
    () => conversations.map((conversation) => `${conversation.id}\u0001${conversation.messages?.map((m) => m.id).join(',') ?? ''}`).join('\u0000'),
    [conversations],
  );
  const [threads, setThreads] = useState<Record<string, ChatMessage[]>>(() => Object.fromEntries(conversations.map((conversation) => [conversation.id, [...(conversation.messages ?? [])]])));
  useEffect(() => {
    setThreads(Object.fromEntries(conversations.map((conversation) => [conversation.id, [...(conversation.messages ?? [])]])));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [signature]);

  // Messages that were not in the first paint pop in; the opening ones belong
  // to the thread's group reveal instead.
  const painted = useRef<Set<string> | null>(null);
  if (painted.current === null) painted.current = new Set(Object.values(threads).flat().map((message) => message.id));
  const isFresh = (message: ChatMessage) => !painted.current!.has(message.id);

  // The relative times in the column stay honest while the page is open.
  useEffect(() => {
    const timer = setInterval(() => setNow(Date.now()), 30_000);
    return () => clearInterval(timer);
  }, []);

  useEffect(() => (area.current ? autogrow(area.current) : undefined), []);

  const filtered = useMemo(() => {
    const q = foldSearchText(query.trim());
    return q ? conversations.filter((conversation) => foldSearchText(`${conversation.name} ${typeof conversation.preview === 'string' ? conversation.preview : ''}`).includes(q)) : conversations;
  }, [conversations, query]);

  const active = conversations.find((conversation) => conversation.id === current) ?? conversations[0];
  const messages = (active && threads[active.id]) || [];
  const typing = active?.typing ? word('typing', { name: active.name }) : null;

  // New messages and the typing indicator keep the thread glued to its end.
  const lastMessage = messages[messages.length - 1];
  const pinned = [current, lastMessage?.id, active?.typing].join('\u0000');
  const previousConversation = useRef<string | null>(null);
  useIsoLayoutEffect(() => {
    const el = thread.current;
    if (!el) return;
    // Switching threads lands at the end at once; new messages glide there.
    const behavior = previousConversation.current !== current || prefersReducedMotion() ? 'auto' : 'smooth';
    previousConversation.current = current;
    el.scrollTo({ top: el.scrollHeight, behavior });
  }, [pinned, thread]);

  const select = (id: string) => {
    if (id === current) return;
    setCurrent(id);
    setRead((state) => ({ ...state, [id]: true }));
    // The unread badge of the thread we just left stays; this one does not.
    setQuery('');
  };

  const send = () => {
    const text = draft.trim();
    if (!text || disabled || !active) return;
    const id = `${base}-sent-${(sequence.current += 1)}`;
    setThreads((state) => ({ ...state, [active.id]: [...(state[active.id] ?? []), { id, side: 'out', text, time: Date.now() }] }));
    setDraft('');
    // The autogrow listens for input events; tell it the field emptied.
    area.current?.dispatchEvent(new Event('input', { bubbles: false }));
    onSend?.(text, active.id);
  };

  const onListKey = (event: KeyboardEvent<HTMLUListElement>) => {
    roveFocus(event.nativeEvent, event.currentTarget, '.nx-chat-conversation', { orientation: 'vertical' });
  };

  const onComposerKey = (event: KeyboardEvent<HTMLTextAreaElement>) => {
    if (event.key === 'Enter' && !event.shiftKey && !event.nativeEvent.isComposing) {
      event.preventDefault();
      send();
    }
  };

  const unreadOf = (conversation: ChatConversation) => (read[conversation.id] || conversation.id === current ? 0 : conversation.unread ?? 0);
  const number = useMemo(() => new Intl.NumberFormat(intl), [intl]);

  return (
    <section className={cx('nx-chat', className)} style={{ ...(height ? vars({ '--nx-chat-height': height }) : null), ...style }} {...rest}>
      <div className="nx-chat-frame">
        <aside className="nx-chat-side">
          <div className="nx-chat-search">
            <Icon name="search" />
            <input
              className="nx-chat-search-input"
              type="search"
              aria-label={searchPlaceholder ?? t('search')}
              placeholder={searchPlaceholder ?? t('search')}
              autoComplete="off"
              value={query}
              onChange={(event) => setQuery(event.target.value)}
            />
          </div>
          {conversations.length === 0 ? (
            <p className="nx-chat-empty">{emptyText ?? word('empty')}</p>
          ) : (
            <ul className="nx-chat-list" role="listbox" aria-label={word('conversations')} onKeyDown={onListKey}>
              {filtered.map((conversation) => {
                const unread = unreadOf(conversation);
                const time = conversation.time !== undefined ? activityTime(conversation.time, now, intl) : null;
                return (
                  <li key={conversation.id} role="presentation">
                    <button
                      type="button"
                      className="nx-chat-conversation"
                      role="option"
                      aria-selected={conversation.id === active?.id}
                      aria-label={unread ? `${conversation.name} (${number.format(unread)} ${word('unread')})` : conversation.name}
                      onClick={() => select(conversation.id)}
                    >
                      <Avatar name={conversation.name} src={conversation.avatar} status={conversation.status} />
                      <span className="nx-chat-cell">
                        <span className="nx-chat-row">
                          <span className="nx-chat-name">{conversation.name}</span>
                          {time && <time className="nx-chat-time" dateTime={isoOf(conversation.time)}>{time}</time>}
                        </span>
                        <span className="nx-chat-row">
                          <span className="nx-chat-preview">{conversation.preview}</span>
                          {unread > 0 && <span className="nx-chat-unread" aria-hidden="true">{number.format(unread)}</span>}
                        </span>
                      </span>
                    </button>
                  </li>
                );
              })}
              {filtered.length === 0 && (
                <li role="presentation">
                  <p className="nx-chat-empty">{t('noResults')}</p>
                </li>
              )}
            </ul>
          )}
        </aside>

        <div className="nx-chat-main">
          {active ? (
            <div className="nx-chat-panel" data-conversation={active.id}>
              <header className="nx-chat-head">
                <Avatar name={active.name} src={active.avatar} status={active.status} />
                <div className="nx-chat-head-meta">
                  <span className="nx-chat-head-name">{active.name}</span>
                  {active.role && <span className="nx-chat-head-role">{active.role}</span>}
                </div>
              </header>
              <div ref={thread} className="nx-chat-thread" role="log" aria-live="polite" aria-label={word('messages')} data-nx-reveal="group">
                {messages.map((message, i) => {
                  const previous = messages[i - 1];
                  const day = message.day ?? dayOf(message.time, intl);
                  const previousDay = previous ? previous.day ?? dayOf(previous.time, intl) : null;
                  const clock = clockOf(message.time, intl);
                  const grouped = !!previous && previous.side === message.side && day === previousDay;
                  return (
                    <Fragment key={message.id}>
                      {day !== previousDay && (
                        <div className="nx-chat-day">
                          <span>{day}</span>
                        </div>
                      )}
                      <div className="nx-chat-message" data-side={message.side} data-grouped={grouped ? '' : undefined} data-fresh={isFresh(message) ? '' : undefined}>
                        <div className="nx-chat-bubble">
                          {message.text}
                          {clock && <time className="nx-chat-message-time" dateTime={isoOf(message.time)}>{clock}</time>}
                        </div>
                      </div>
                    </Fragment>
                  );
                })}
                {typing && (
                  <p className="nx-chat-typing" data-open="">
                    <span className="nx-chat-typing-dots" aria-hidden="true">
                      <i />
                      <i />
                      <i />
                    </span>
                    {typing}
                  </p>
                )}
                {messages.length === 0 && !typing && <p className="nx-chat-empty">{word('noMessages')}</p>}
              </div>
            </div>
          ) : (
            <div className="nx-chat-panel">
              <p className="nx-chat-empty">{emptyText ?? word('empty')}</p>
            </div>
          )}

          <form
            className="nx-chat-composer"
            onSubmit={(event) => {
              event.preventDefault();
              send();
            }}
          >
            <textarea
              ref={area}
              className="nx-chat-input"
              rows={1}
              aria-label={placeholder ?? word('messagePlaceholder')}
              placeholder={placeholder ?? word('messagePlaceholder')}
              disabled={disabled || !active}
              value={draft}
              onChange={(event) => setDraft(event.target.value)}
              onKeyDown={onComposerKey}
            />
            <button type="submit" className="nx-chat-send" data-ready={draft.trim() ? '' : undefined} disabled={disabled || !draft.trim() || !active} aria-label={t('send')}>
              <Icon name="arrow-up" />
            </button>
          </form>
        </div>
      </div>
    </section>
  );
}

// apps/admin-svelte/src/lib/Chat.svelte
<script lang="ts" module>
  export type ChatPresence = 'online' | 'busy' | 'away' | 'offline';

  export interface ChatMessage {
    id: string;
    /** Incoming (them) or outgoing (me); sides mirror themselves in RTL. */
    side: 'in' | 'out';
    text: string;
    /** A timestamp; any other string is shown as it is. */
    time?: Date | number | string;
  }

  export interface ChatConversation {
    id: string;
    name: string;
    status?: ChatPresence;
    /** Who they are, under the name in the thread header. */
    role?: string;
    /** The last line, shown in the conversations column. */
    preview?: string;
    time?: Date | number | string;
    unread?: number;
    /** Show the three-dot indicator in this thread. */
    typing?: boolean;
    messages?: ChatMessage[];
  }
</script>

<script lang="ts">
  /**
   * The chat block — the hand-written Svelte shape of `nx-chat`: a
   * conversations column (live search + unread, core `foldSearchText` and
   * `roveFocus`) beside one message thread — bubbles that pop in, day
   * separators, a growing composer (core `autogrow`) and the three-dot typing
   * indicator. Sending echoes the message into the thread locally; there is no
   * backend to talk to. The words the block says come from the core i18n table.
   */
  import { onMount, tick } from 'svelte';
  import { activityTime, autogrow, type Cleanup, foldSearchText, prefersReducedMotion, reveal, roveFocus, timeOf, translate } from '@nabuxai/ui-core';
  import { app, intlLocale } from '../store.svelte';
  import Avatar from './Avatar.svelte';
  import NxIcon from './NxIcon.svelte';

  let {
    conversations,
    value = $bindable(undefined),
    onsend = undefined,
    searchPlaceholder = undefined,
    placeholder = undefined,
    emptyText = undefined,
    height = '34rem',
    ariaLabel = undefined,
  }: {
    conversations: ChatConversation[];
    value?: string;
    onsend?: (text: string, conversationId: string) => void;
    searchPlaceholder?: string;
    placeholder?: string;
    emptyText?: string;
    height?: string;
    ariaLabel?: string;
  } = $props();

  const intl = $derived(intlLocale());
  const word = (key: 'search' | 'send' | 'noResults' | 'chatConversations' | 'chatMessages' | 'chatMessagePlaceholder' | 'chatTyping' | 'chatUnread' | 'chatEmpty' | 'chatNoMessages', params: Record<string, string | number> = {}) =>
    translate(app.lang, key, params);

  // The open thread starts at the (bound or) first conversation; afterwards the list owns it.
  // svelte-ignore state_referenced_locally
  let current = $state(value ?? conversations[0]?.id ?? '');
  let query = $state('');
  let draft = $state('');
  let read = $state<Record<string, true>>({});
  let now = $state(Date.now());
  /** Messages sent from this page, echoed per conversation (the seeds come from props). */
  let sent = $state<Record<string, ChatMessage[]>>({});
  let sequence = 0;

  // Bound inside an {#if}, so the binding writes again as threads come and go.
  let thread = $state<HTMLDivElement | undefined>(undefined);
  let area: HTMLTextAreaElement;
  let stopGrow: Cleanup | null = null;
  let stopReveal: Cleanup | null = null;
  let timer: ReturnType<typeof setInterval> | undefined;
  let previousConversation: string | null = null;

  const filtered = $derived.by(() => {
    const q = foldSearchText(query.trim());
    return q ? conversations.filter((conversation) => foldSearchText(`${conversation.name} ${conversation.preview ?? ''}`).includes(q)) : conversations;
  });

  const active = $derived(conversations.find((conversation) => conversation.id === current) ?? conversations[0]);
  /** The thread: the seeded messages plus everything sent here, in order. */
  const messages = $derived([...(active?.messages ?? []), ...(sent[active?.id ?? ''] ?? [])]);
  const typingWord = $derived(active?.typing ? word('chatTyping', { name: active.name }) : null);
  const numberFmt = $derived(new Intl.NumberFormat(intl));

  // The relative times in the column stay honest while the page is open; the
  // thread's opening messages rise one after another (a one-shot group reveal).
  onMount(() => {
    stopGrow = autogrow(area);
    if (thread) stopReveal = reveal(thread, { stagger: true, once: true });
    timer = setInterval(() => (now = Date.now()), 30_000);
    return () => {
      stopGrow?.();
      stopReveal?.();
      clearInterval(timer);
    };
  });

  // New messages and the typing indicator keep the thread glued to its end.
  const lastMessage = $derived(messages[messages.length - 1]);
  $effect(() => {
    void current;
    void lastMessage?.id;
    void active?.typing;
    if (!thread) return;
    void tick().then(() => {
      // Switching threads lands at the end at once; new messages glide there.
      const behavior = previousConversation !== current || prefersReducedMotion() ? 'auto' : 'smooth';
      previousConversation = current;
      thread?.scrollTo({ top: thread.scrollHeight, behavior });
    });
  });

  const select = (id: string) => {
    if (id === current) return;
    current = id;
    value = id;
    read = { ...read, [id]: true };
    query = '';
  };

  const send = () => {
    const text = draft.trim();
    if (!text || !active) return;
    sequence += 1;
    const id = `sent-${sequence}`;
    sent = { ...sent, [active.id]: [...(sent[active.id] ?? []), { id, side: 'out', text, time: Date.now() }] };
    draft = '';
    // The autogrow listens for input events; tell it the field emptied.
    area?.dispatchEvent(new Event('input', { bubbles: false }));
    onsend?.(text, active.id);
  };

  const onComposerKey = (event: KeyboardEvent) => {
    if (event.key === 'Enter' && !event.shiftKey && !event.isComposing) {
      event.preventDefault();
      send();
    }
  };

  const onListKey = (event: KeyboardEvent) => roveFocus(event, event.currentTarget as HTMLElement, '.nx-chat-conversation', { orientation: 'vertical' });

  const unreadOf = (conversation: ChatConversation) => (read[conversation.id] || conversation.id === current ? 0 : conversation.unread ?? 0);

  /** "10:24" for anything that parses as a moment; anything else shows as it is. */
  function clockOf(time: Date | number | string | undefined): string | null {
    if (time === undefined) return null;
    const at = timeOf(time);
    return Number.isNaN(at) ? (typeof time === 'string' ? time : null) : new Intl.DateTimeFormat(intl, { hour: 'numeric', minute: '2-digit' }).format(at);
  }

  /** The day a message belongs to, in the reader's calendar. */
  function dayOf(time: Date | number | string | undefined): string | null {
    if (time === undefined) return null;
    const at = timeOf(time);
    return Number.isNaN(at) ? null : new Intl.DateTimeFormat(intl, { dateStyle: 'medium' }).format(at);
  }

  const isoOf = (time: Date | number | string | undefined) => {
    if (time === undefined) return undefined;
    const at = timeOf(time);
    return Number.isNaN(at) ? undefined : new Date(at).toISOString();
  };
</script>

<section class="nx-chat" style:--nx-chat-height={height} aria-label={ariaLabel}>
  <div class="nx-chat-frame">
    <aside class="nx-chat-side">
      <div class="nx-chat-search">
        <NxIcon name="search" />
        <input
          class="nx-chat-search-input"
          type="search"
          aria-label={searchPlaceholder ?? word('search')}
          placeholder={searchPlaceholder ?? word('search')}
          autocomplete="off"
          bind:value={query}
        />
      </div>
      {#if conversations.length === 0}
        <p class="nx-chat-empty">{emptyText ?? word('chatEmpty')}</p>
      {:else}
        <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
        <ul class="nx-chat-list" role="listbox" aria-label={word('chatConversations')} onkeydown={onListKey}>
          {#each filtered as conversation (conversation.id)}
            {@const unread = unreadOf(conversation)}
            {@const time = conversation.time !== undefined ? activityTime(conversation.time, now, intl) : null}
            <li role="presentation">
              <button
                type="button"
                class="nx-chat-conversation"
                role="option"
                aria-selected={conversation.id === active?.id}
                aria-label={unread ? `${conversation.name} (${numberFmt.format(unread)} ${word('chatUnread')})` : conversation.name}
                onclick={() => select(conversation.id)}
              >
                <Avatar name={conversation.name} status={conversation.status} />
                <span class="nx-chat-cell">
                  <span class="nx-chat-row">
                    <span class="nx-chat-name">{conversation.name}</span>
                    {#if time}<time class="nx-chat-time" datetime={isoOf(conversation.time)}>{time}</time>{/if}
                  </span>
                  <span class="nx-chat-row">
                    <span class="nx-chat-preview">{conversation.preview}</span>
                    {#if unread > 0}<span class="nx-chat-unread" aria-hidden="true">{numberFmt.format(unread)}</span>{/if}
                  </span>
                </span>
              </button>
            </li>
          {/each}
          {#if filtered.length === 0}
            <li role="presentation">
              <p class="nx-chat-empty">{word('noResults')}</p>
            </li>
          {/if}
        </ul>
      {/if}
    </aside>

    <div class="nx-chat-main">
      {#if active}
        <div class="nx-chat-panel" data-conversation={active.id}>
          <header class="nx-chat-head">
            <Avatar name={active.name} status={active.status} />
            <div class="nx-chat-head-meta">
              <span class="nx-chat-head-name">{active.name}</span>
              {#if active.role}<span class="nx-chat-head-role">{active.role}</span>{/if}
            </div>
          </header>
          <div bind:this={thread} class="nx-chat-thread" role="log" aria-live="polite" aria-label={word('chatMessages')} data-nx-reveal="group">
            {#each messages as message, i (message.id)}
              {@const previous = messages[i - 1]}
              {@const day = dayOf(message.time)}
              {@const previousDay = previous ? dayOf(previous.time) : null}
              {@const clock = clockOf(message.time)}
              {@const grouped = !!previous && previous.side === message.side && day === previousDay}
              {#if day !== previousDay}
                <div class="nx-chat-day">
                  <span>{day}</span>
                </div>
              {/if}
              <div class="nx-chat-message" data-side={message.side} data-grouped={grouped ? '' : undefined} data-fresh={message.id.startsWith('sent-') ? '' : undefined}>
                <div class="nx-chat-bubble">
                  {message.text}
                  {#if clock}<time class="nx-chat-message-time" datetime={isoOf(message.time)}>{clock}</time>{/if}
                </div>
              </div>
            {/each}
            {#if typingWord}
              <p class="nx-chat-typing" data-open="">
                <span class="nx-chat-typing-dots" aria-hidden="true">
                  <i></i>
                  <i></i>
                  <i></i>
                </span>
                {typingWord}
              </p>
            {/if}
            {#if messages.length === 0 && !typingWord}
              <p class="nx-chat-empty">{word('chatNoMessages')}</p>
            {/if}
          </div>
        </div>
      {:else}
        <div class="nx-chat-panel">
          <p class="nx-chat-empty">{emptyText ?? word('chatEmpty')}</p>
        </div>
      {/if}

      <form
        class="nx-chat-composer"
        onsubmit={(event) => {
          event.preventDefault();
          send();
        }}
      >
        <textarea
          bind:this={area}
          class="nx-chat-input"
          rows="1"
          aria-label={placeholder ?? word('chatMessagePlaceholder')}
          placeholder={placeholder ?? word('chatMessagePlaceholder')}
          disabled={!active}
          bind:value={draft}
          onkeydown={onComposerKey}
        ></textarea>
        <button type="submit" class="nx-chat-send" data-ready={draft.trim() ? '' : undefined} disabled={!draft.trim() || !active} aria-label={word('send')}>
          <NxIcon name="arrow-up" />
        </button>
      </form>
    </div>
  </div>
</section>
