// apps/admin-vue/src/components/DataTable.vue
<script setup lang="ts" generic="R">
/**
 * The data table — the hand-written Vue twin of the `data-table` block
 * (nx-data-table): sorting through the core `sortRows`/`nextSort` pair and the
 * FLIP glide (`snapshotRows` + `playRowFlip`) after each sort, the group reveal
 * on mount, and a keyboard-scrollable box when the table overflows. Cells are
 * the page's: `#cell-<key>` slots, headers `#head-<key>`.
 */
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import {
  type SortState,
  nextSort,
  playRowFlip,
  reveal,
  snapshotRows,
  sortRows,
} from '@nabuxai/ui-core';
import { intlLocale } from '../store';

export interface Column<R> {
  key: string;
  label: string;
  sortable?: boolean;
  sortValue?: (row: R) => unknown;
  align?: 'start' | 'end';
  width?: string;
}

const props = withDefaults(
  defineProps<{
    rows: R[];
    columns: Column<R>[];
    rowKey?: (row: R, index: number) => string;
    caption: string;
    emptyText?: string;
    defaultSort?: SortState | null;
    maxHeight?: string;
  }>(),
  { rowKey: undefined, emptyText: undefined, defaultSort: null, maxHeight: undefined },
);

const scroller = ref<HTMLDivElement | null>(null);
const body = ref<HTMLTableSectionElement | null>(null);
const sort = ref<SortState | null>(props.defaultSort);
const scrollable = ref(false);
let flight: ReturnType<typeof snapshotRows> | null = null;
let stopReveal: (() => void) | null = null;

const keyOf = (row: R, index: number) => (props.rowKey ? props.rowKey(row, index) : String(index));

const sorted = computed(() => {
  if (!sort.value) return props.rows;
  const column = props.columns.find((c) => c.key === sort.value!.key);
  const value = column?.sortValue ? (row: R) => column.sortValue!(row) : undefined;
  return sortRows(props.rows, sort.value.key, sort.value.direction, { locale: intlLocale.value, value });
});

/** The fallback cell text when the page does not provide a slot for the column. */
const cellText = (row: R, column: Column<R>) => String((row as Record<string, unknown>)[column.key] ?? '');

onMounted(() => {
  if (scroller.value) stopReveal = reveal(scroller.value, { once: true });
  checkScroll();
});
onBeforeUnmount(() => stopReveal?.());

// A table wider or taller than its box can be scrolled from the keyboard.
function checkScroll() {
  const el = scroller.value;
  if (!el || typeof ResizeObserver === 'undefined') return;
  scrollable.value = el.scrollWidth > el.clientWidth + 1 || el.scrollHeight > el.clientHeight + 1;
}

const press = (key: string) => {
  if (body.value) flight = snapshotRows(Array.from(body.value.rows));
  sort.value = nextSort(sort.value, key);
  // A sort that lands on the same key still re-renders; drop stale snapshots.
  requestAnimationFrame(() => (flight = null));
};

watch(sort, () => void nextTick(flip));

function flip() {
  if (!flight || !body.value) return;
  const before = flight;
  flight = null;
  playRowFlip(Array.from(body.value.rows), before);
}

const directionOf = (key: string) => (sort.value?.key === key ? sort.value.direction : undefined);
</script>

<template>
  <div
    ref="scroller"
    class="nx-data-table"
    data-nx-reveal=""
    :tabindex="scrollable ? 0 : undefined"
    :role="scrollable ? 'region' : undefined"
    :aria-label="scrollable ? caption : undefined"
    :style="maxHeight ? { '--nx-table-max': maxHeight } : undefined"
    @resize="checkScroll"
  >
    <table>
      <caption class="nx-visually-hidden">{{ caption }}</caption>
      <thead>
        <tr>
          <th
            v-for="column in columns"
            :key="column.key"
            scope="col"
            :aria-sort="directionOf(column.key)"
            :data-align="column.align && column.align !== 'start' ? column.align : undefined"
            :style="column.width ? { inlineSize: column.width } : undefined"
          >
            <slot :name="`head-${column.key}`" :column="column">
              <button
                v-if="column.sortable"
                type="button"
                class="nx-data-table-sort"
                :data-direction="directionOf(column.key)"
                @click="press(column.key)"
              >
                <span>{{ column.label }}</span>
                <svg class="nx-data-table-sort-icon" viewBox="0 0 24 24" aria-hidden="true">
                  <path d="M12 19V5M6 11l6-6 6 6" />
                </svg>
              </button>
              <template v-else>{{ column.label }}</template>
            </slot>
          </th>
        </tr>
      </thead>
      <tbody ref="body">
        <tr v-if="sorted.length === 0">
          <td class="nx-data-table-empty" :colspan="columns.length">{{ emptyText }}</td>
        </tr>
        <tr v-for="(row, index) in sorted" :key="keyOf(row, index)" :data-key="keyOf(row, index)" :style="{ '--nx-i': index }">
          <td
            v-for="column in columns"
            :key="column.key"
            :data-align="column.align && column.align !== 'start' ? column.align : undefined"
          >
            <slot :name="`cell-${column.key}`" :row="row" :index="index">{{ cellText(row, column) }}</slot>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

// apps/admin-svelte/src/lib/DataTable.svelte
<script lang="ts" module>
  import type { Snippet } from 'svelte';
  import type { SortState } from '@nabuxai/ui-core';

  export interface Column<R> {
    key: string;
    label: string;
    sortable?: boolean;
    sortValue?: (row: R) => unknown;
    align?: 'start' | 'end';
    width?: string;
    /** The page's own cell renderer for this column. */
    cell?: Snippet<[row: R, index: number]>;
    /** The page's own header renderer (the select-all checkbox). */
    head?: Snippet<[column: Column<R>]>;
  }

  export type { SortState };
</script>

<script lang="ts">
  /**
   * The data table — the hand-written Svelte twin of the `data-table` block
   * (nx-data-table): sorting through the core `sortRows`/`nextSort` pair and
   * the FLIP glide (`snapshotRows` + `playRowFlip`) after each sort, the group
   * reveal on mount, and a keyboard-scrollable box when the table overflows.
   * Cells come in as per-column snippets on the column definitions. The row
   * type stays open (`unknown`) — the page instantiates `Column<ItsRow>`.
   */
  import { onMount, tick } from 'svelte';
  import { nextSort, playRowFlip, reveal, snapshotRows, sortRows, type RowSnapshot } from '@nabuxai/ui-core';
  import { intlLocale } from '../store.svelte';

  /* eslint-disable @typescript-eslint/no-explicit-any -- Svelte components have no generics; the page types its own rows. */
  let {
    rows,
    columns,
    class: className = undefined,
    rowKey = undefined,
    caption,
    emptyText = undefined,
    defaultSort = null,
    maxHeight = undefined,
  }: {
    rows: any[];
    columns: Column<any>[];
    class?: string;
    rowKey?: (row: any, index: number) => string;
    caption: string;
    emptyText?: string;
    defaultSort?: SortState | null;
    maxHeight?: string;
  } = $props();

  let scroller: HTMLDivElement;
  let body: HTMLTableSectionElement;
  // The initial sort comes from the page; afterwards the header presses own it.
  // svelte-ignore state_referenced_locally
  let sort = $state<SortState | null>(defaultSort);
  let scrollable = $state(false);
  let flight: RowSnapshot | null = null;

  const keyOf = (row: any, index: number) => (rowKey ? rowKey(row, index) : String(index));

  const sorted = $derived.by(() => {
    if (!sort) return rows;
    const current = sort;
    const column = columns.find((c) => c.key === current.key);
    const value = column?.sortValue ? (row: any) => column.sortValue!(row) : undefined;
    return sortRows(rows, current.key, current.direction, { locale: intlLocale(), value });
  });

  onMount(() => {
    const stop = reveal(scroller, { once: true });
    checkScroll();
    return stop;
  });

  // A table wider or taller than its box can be scrolled from the keyboard.
  function checkScroll() {
    if (!scroller) return;
    scrollable = scroller.scrollWidth > scroller.clientWidth + 1 || scroller.scrollHeight > scroller.clientHeight + 1;
  }

  const press = async (key: string) => {
    if (body) flight = snapshotRows(Array.from(body.rows));
    sort = nextSort(sort, key);
    await tick();
    flip();
    requestAnimationFrame(() => (flight = null));
  };

  function flip() {
    if (!flight || !body) return;
    const before = flight;
    flight = null;
    playRowFlip(Array.from(body.rows), before);
  }

  const directionOf = (key: string) => (sort?.key === key ? sort.direction : undefined);
</script>

<!-- svelte-ignore a11y_no_noninteractive_tabindex, a11y_no_static_element_interactions -->
<div
  bind:this={scroller}
  class={className ? `nx-data-table ${className}` : 'nx-data-table'}
  data-nx-reveal=""
  tabindex={scrollable ? 0 : undefined}
  role={scrollable ? 'region' : undefined}
  aria-label={scrollable ? caption : undefined}
  style:--nx-table-max={maxHeight}
>
  <table>
    <caption class="nx-visually-hidden">{caption}</caption>
    <thead>
      <tr>
        {#each columns as column (column.key)}
          <th
            scope="col"
            aria-sort={directionOf(column.key)}
            data-align={column.align && column.align !== 'start' ? column.align : undefined}
            style={column.width ? `inline-size: ${column.width}` : undefined}
          >
            {#if column.head}
              {@render column.head(column)}
            {:else if column.sortable}
              <button type="button" class="nx-data-table-sort" data-direction={directionOf(column.key)} onclick={() => press(column.key)}>
                <span>{column.label}</span>
                <svg class="nx-data-table-sort-icon" viewBox="0 0 24 24" aria-hidden="true">
                  <path d="M12 19V5M6 11l6-6 6 6" />
                </svg>
              </button>
            {:else}
              {column.label}
            {/if}
          </th>
        {/each}
      </tr>
    </thead>
    <tbody bind:this={body}>
      {#if sorted.length === 0}
        <tr><td class="nx-data-table-empty" colspan={columns.length}>{emptyText}</td></tr>
      {/if}
      {#each sorted as row, index (keyOf(row, index))}
        <tr data-key={keyOf(row, index)} style:--nx-i={index}>
          {#each columns as column (column.key)}
            <td data-align={column.align && column.align !== 'start' ? column.align : undefined}>
              {#if column.cell}{@render column.cell(row, index)}{:else}{row[column.key]}{/if}
            </td>
          {/each}
        </tr>
      {/each}
    </tbody>
  </table>
</div>
