// packages/react/src/blocks/kanban.tsx
/**
 * Kanban — a column board with native HTML5 drag & drop (React).
 *
 * Thin over css/blocks/kanban.css. Cards are reordered by dragging (or by the
 * "Move to …" items in each card's three-dot menu, which keeps reordering
 * keyboard reachable) and glide with the core FLIP helpers; the drop point is
 * shown by a breathing placeholder pill, column counts roll as digits
 * (numberParts/localeDigits) and the quick-add composer grows in place. State
 * is the columns you pass: controlled (`columns` + `onColumnsChange`) or
 * uncontrolled (`defaultColumns`), with `onMove` / `onAdd` detail callbacks.
 */
import {
  type CSSProperties,
  type DragEvent as ReactDragEvent,
  type FormEvent,
  type HTMLAttributes,
  type ReactNode,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
} from 'react';
import type { IconName } from '@nabuxai/ui-core';
import { place, playRowFlip, reveal, roveFocus, snapshotRows } from '@nabuxai/ui-core';
import { cx, useBehavior, useControllable, useEvent, useIsoLayoutEffect } from '../internal/hooks';
import { Icon } from '../internal/icon';
import { SmartLink, useLocale, useT } from '../internal/provider';
import { Avatar } from '../components/display';
import { NumberTicker } from '../components/text';

/** The Intl locale: the prop, or the provider's language. */
const INTL = { en: 'en-US', fa: 'fa-IR', ar: 'ar' } as const;

/* ---- Types ---------------------------------------------------------------------------- */

export type KanbanTone = 'accent' | 'success' | 'warning' | 'danger' | 'info' | 'gold';

export interface KanbanCardAction {
  label: ReactNode;
  icon?: IconName;
  /** Destructive actions read in the danger colour. */
  danger?: boolean;
  href?: string;
  onSelect?: () => void;
}

export interface KanbanCard {
  id: string;
  title: string;
  description?: string;
  tone?: KanbanTone;
  /** A small line under the title — free text ("Due Friday · 2 comments"). */
  meta?: string;
  assignee?: { name: string; src?: string };
  /** The three-dot menu items; the menu appears when a card has any. */
  actions?: KanbanCardAction[];
}

export interface KanbanColumn {
  id: string;
  title: string;
  tone?: KanbanTone;
  cards: KanbanCard[];
}

export interface KanbanMove {
  card: string;
  from: string;
  to: string;
  index: number;
}

export interface KanbanProps extends Omit<HTMLAttributes<HTMLElement>, 'children'> {
  columns?: KanbanColumn[];
  defaultColumns?: KanbanColumn[];
  onColumnsChange?: (columns: KanbanColumn[]) => void;
  /** Fired for every reorder, whichever way it started (drag or menu). */
  onMove?: (move: KanbanMove, columns: KanbanColumn[]) => void;
  /** Fired when the quick-add composer adds a card. */
  onAdd?: (column: string, title: string, columns: KanbanColumn[]) => void;
  /** Show the per-column quick-add composer (default). */
  quickAdd?: boolean;
  addPlaceholder?: string;
  /** The board's accessible name. */
  label?: string;
  /** Overall board height; each column scrolls inside ("36rem"). */
  height?: string;
  locale?: string;
}

const vars = (style: Record<string, string | number | undefined>) => style as CSSProperties;

const DOTS = 'M12 5.25h.01M12 12h.01M12 18.75h.01';

/** Where a pointer's Y falls in `list`: before which card (its index, or the end). */
function dropIndex(list: HTMLElement, dragging: HTMLElement | null, y: number): number {
  const cards = Array.from(list.querySelectorAll<HTMLElement>('.nx-kanban-card')).filter((card) => card !== dragging);
  for (let i = 0; i < cards.length; i++) {
    const rect = cards[i]!.getBoundingClientRect();
    if (y < rect.top + rect.height / 2) return i;
  }
  return cards.length;
}

export function Kanban({
  columns: controlled,
  defaultColumns,
  onColumnsChange,
  onMove,
  onAdd,
  quickAdd = true,
  addPlaceholder,
  label,
  height,
  locale,
  className,
  style,
  ...rest
}: KanbanProps) {
  const t = useT();
  const language = useLocale();
  const number = useMemo(() => new Intl.NumberFormat(locale ?? INTL[language]), [locale, language]);
  const base = `nx-kanban${useId().replace(/:/g, '')}`;
  const [columns, setColumns] = useControllable(controlled, defaultColumns ?? [], onColumnsChange);
  const [dragging, setDragging] = useState<string | null>(null);
  const [over, setOver] = useState<{ column: string; index: number } | null>(null);
  const [adding, setAdding] = useState<string | null>(null);
  const [announced, setAnnounced] = useState('');
  const board = useRef<HTMLElement>(null);
  const flight = useRef<ReturnType<typeof snapshotRows> | null>(null);
  useBehavior(board, reveal, { once: true });

  const cardsOf = () => board.current?.querySelectorAll<HTMLElement>('.nx-kanban-card[data-key]') ?? [];

  // Reorders arrive from drops and from card menus alike; both carry the same FLIP.
  const commit = useEvent((move: KanbanMove) => {
    const next = columns.map((col) => ({ ...col, cards: [...col.cards] }));
    const from = next.find((col) => col.id === move.from);
    const to = next.find((col) => col.id === move.to);
    const card = from?.cards.find((c) => c.id === move.card);
    if (!from || !to || !card) return;
    from.cards = from.cards.filter((c) => c.id !== move.card);
    to.cards.splice(Math.max(0, Math.min(move.index, to.cards.length)), 0, card);
    flight.current = snapshotRows(cardsOf());
    setColumns(next);
    onMove?.(move, next);
    setAnnounced(t('kanbanMovedTo', { card: card.title, column: to.title }));
  });

  useIsoLayoutEffect(() => {
    if (!flight.current) return;
    const before = flight.current;
    flight.current = null;
    playRowFlip(cardsOf(), before);
  }, [columns]);

  /* ---- Native drag & drop ----------------------------------------------------------------- */

  const onDragStart = (event: ReactDragEvent<HTMLLIElement>, card: string) => {
    event.dataTransfer.setData('text/plain', card);
    event.dataTransfer.effectAllowed = 'move';
    setDragging(card);
  };

  const onDragOver = (event: ReactDragEvent<HTMLUListElement>, column: string) => {
    if (!dragging) return;
    event.preventDefault();
    event.dataTransfer.dropEffect = 'move';
    const source = board.current?.querySelector<HTMLElement>(`.nx-kanban-card[data-key="${CSS.escape(dragging)}"]`) ?? null;
    const index = dropIndex(event.currentTarget, source, event.clientY);
    setOver((current) => (current?.column === column && current.index === index ? current : { column, index }));
  };

  const onDrop = (event: ReactDragEvent<HTMLUListElement>, column: string) => {
    event.preventDefault();
    const card = dragging ?? event.dataTransfer.getData('text/plain');
    const from = columns.find((col) => col.cards.some((c) => c.id === card))?.id;
    setDragging(null);
    setOver(null);
    if (!from) return;
    const source = board.current?.querySelector<HTMLElement>(`.nx-kanban-card[data-key="${CSS.escape(card)}"]`) ?? null;
    commit({ card, from, to: column, index: dropIndex(event.currentTarget, source, event.clientY) });
  };

  const onDragLeave = (event: ReactDragEvent<HTMLUListElement>, column: string) => {
    if (event.currentTarget.contains(event.relatedTarget as Node | null)) return;
    setOver((current) => (current?.column === column ? null : current));
  };

  /* ---- Quick add -------------------------------------------------------------------------- */

  const submit = (event: FormEvent<HTMLFormElement>, column: string) => {
    event.preventDefault();
    const input = event.currentTarget.elements.namedItem('title') as HTMLInputElement | null;
    const title = input?.value.trim();
    if (!title) {
      input?.focus();
      return;
    }
    const id = `card-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`;
    const next = columns.map((col) => (col.id === column ? { ...col, cards: [...col.cards, { id, title }] } : col));
    flight.current = snapshotRows(cardsOf());
    setColumns(next);
    onAdd?.(column, title, next);
    if (input) input.value = '';
    input?.focus();
  };

  return (
    <section
      ref={board}
      className={cx('nx-kanban', className)}
      aria-label={label ?? t('kanbanBoard')}
      style={{ ...(height ? vars({ '--nx-kanban-height': height }) : null), ...style }}
      {...rest}
    >
      <div className="nx-kanban-board">
        {columns.map((column) => {
          const heading = `${base}-col-${column.id}`;
          const overHere = over?.column === column.id ? over.index : null;
          // The placeholder sits among the column's *other* cards, so it shows
          // where the dragged card will land once it leaves its old slot.
          const items: ReactNode[] = [];
          let landing = 0;
          column.cards.forEach((card) => {
            if (card.id !== dragging) {
              if (overHere === landing) items.push(<Placeholder key={`ph-${column.id}`} />);
              landing += 1;
            }
            items.push(
              <Card
                key={card.id}
                card={card}
                index={landing}
                dragging={dragging === card.id}
                menuId={`${base}-menu-${card.id}`}
                columns={columns}
                onDragStart={onDragStart}
                onDragEnd={() => {
                  setDragging(null);
                  setOver(null);
                }}
                onMove={commit}
                menuLabel={t('kanbanCardMenu', { name: card.title })}
                moveTo={(name: string) => t('kanbanMoveTo', { column: name })}
              />,
            );
          });
          if (overHere !== null && overHere >= landing) items.push(<Placeholder key={`ph-${column.id}-end`} />);
          return (
            <div
              key={column.id}
              className="nx-kanban-column"
              data-column={column.id}
              data-tone={column.tone}
              data-dropping={overHere !== null ? '' : undefined}
            >
              <header className="nx-kanban-column-head">
                <span className="nx-kanban-column-dot" aria-hidden="true" />
                <h3 className="nx-kanban-column-title" id={heading}>
                  {column.title}
                </h3>
                <span className="nx-kanban-column-count" aria-hidden="true">
                  <NumberTicker value={column.cards.length} reveal={false} locale={locale} />
                </span>
                <span className="nx-visually-hidden">{t('kanbanCards', { count: number.format(column.cards.length) })}</span>
              </header>
              <ul
                className="nx-kanban-list"
                aria-labelledby={heading}
                onDragOver={(event) => onDragOver(event, column.id)}
                onDrop={(event) => onDrop(event, column.id)}
                onDragLeave={(event) => onDragLeave(event, column.id)}
              >
                {items}
                {column.cards.length === 0 && overHere === null && <li className="nx-kanban-empty">{t('kanbanEmpty')}</li>}
              </ul>
              {quickAdd && (
                <div className="nx-kanban-add">
                  <button
                    type="button"
                    className="nx-kanban-add-open"
                    aria-expanded={adding === column.id}
                    aria-controls={`${base}-add-${column.id}`}
                    onClick={() => setAdding(adding === column.id ? null : column.id)}
                  >
                    <Icon name="plus" />
                    <span>{t('kanbanAddCard')}</span>
                  </button>
                  <div className="nx-kanban-add-form" id={`${base}-add-${column.id}`} data-open={adding === column.id ? '' : undefined}>
                    <form className="nx-kanban-add-body" onSubmit={(event) => submit(event, column.id)}>
                      <input
                        className="nx-kanban-add-input"
                        name="title"
                        type="text"
                        autoComplete="off"
                        placeholder={addPlaceholder ?? t('kanbanAddCard')}
                        aria-label={t('kanbanAddCard')}
                      />
                      <button type="submit" className="nx-kanban-add-submit">
                        {t('kanbanAdd')}
                      </button>
                    </form>
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>
      {/* The move, spoken once it lands. */}
      <p className="nx-visually-hidden" role="status">
        {announced}
      </p>
    </section>
  );
}

/* ---- The placeholder pill ---------------------------------------------------------------- */

function Placeholder() {
  return (
    <li className="nx-kanban-placeholder" aria-hidden="true">
      <span className="nx-kanban-placeholder-dot" />
      <span className="nx-kanban-placeholder-bar" />
    </li>
  );
}

/* ---- One card, with its three-dot menu ----------------------------------------------------- */

interface CardProps {
  card: KanbanCard;
  index: number;
  dragging: boolean;
  menuId: string;
  columns: KanbanColumn[];
  onDragStart: (event: ReactDragEvent<HTMLLIElement>, card: string) => void;
  onDragEnd: () => void;
  onMove: (move: KanbanMove) => void;
  menuLabel: string;
  moveTo: (column: string) => string;
}

function Card({ card, index, dragging, menuId, columns, onDragStart, onDragEnd, onMove, menuLabel, moveTo }: CardProps) {
  const [open, setOpen] = useState(false);
  const trigger = useRef<HTMLButtonElement>(null);
  const panel = useRef<HTMLDivElement>(null);
  const from = columns.find((col) => col.cards.some((c) => c.id === card.id))?.id;
  const others = useMemo(() => columns.filter((col) => col.id !== from), [columns, from]);
  const hasMenu = (card.actions?.length ?? 0) > 0 || others.length > 0;

  // The menu is a native popover placed against its trigger (core place).
  useEffect(() => {
    const button = trigger.current;
    if (button && 'popover' in HTMLElement.prototype) button.setAttribute('popovertarget', menuId);
  }, [menuId]);

  useEffect(() => {
    const el = panel.current;
    if (!el) return;
    const onToggle = (event: Event) => setOpen((event as ToggleEvent).newState === 'open');
    el.addEventListener('toggle', onToggle);
    return () => el.removeEventListener('toggle', onToggle);
  }, []);

  useIsoLayoutEffect(() => {
    if (!open || !trigger.current || !panel.current) return;
    return place(trigger.current, panel.current, { side: 'bottom', align: 'end', offset: 6 });
  }, [open]);

  // An exit is softer and faster than the enter: fold away quickly.
  const close = () => window.setTimeout(() => panel.current?.matches(':popover-open') && panel.current?.hidePopover(), 150);

  const choose = (action: KanbanCardAction) => {
    action.onSelect?.();
    close();
  };

  const move = (to: string) => {
    onMove({ card: card.id, from: from ?? '', to, index: columns.find((col) => col.id === to)?.cards.length ?? 0 });
    close();
  };

  return (
    <li
      className="nx-kanban-card"
      data-key={card.id}
      data-tone={card.tone}
      data-dragging={dragging ? '' : undefined}
      style={vars({ '--nx-i': index })}
      draggable
      onDragStart={(event) => onDragStart(event, card.id)}
      onDragEnd={onDragEnd}
    >
      {card.tone && <span className="nx-kanban-card-dot" aria-hidden="true" />}
      <div className="nx-kanban-card-main">
        <p className="nx-kanban-card-title">{card.title}</p>
        {card.meta && <p className="nx-kanban-card-meta">{card.meta}</p>}
      </div>
      {card.assignee && <Avatar name={card.assignee.name} src={card.assignee.src} size="sm" />}
      {hasMenu && (
        <>
          <button
            ref={trigger}
            type="button"
            className="nx-kanban-card-menu"
            aria-haspopup="menu"
            aria-expanded={open}
            aria-controls={menuId}
            aria-label={menuLabel}
            onClick={() => {
              if (!('popover' in HTMLElement.prototype)) setOpen(!open);
            }}
          >
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.75} strokeLinecap="round" aria-hidden="true">
              <path d={DOTS} />
            </svg>
          </button>
          <div
            ref={panel}
            id={menuId}
            className="nx-kanban-menu"
            role="menu"
            aria-label={menuLabel}
            {...{ popover: 'auto' }}
            onKeyDown={(event) => roveFocus(event.nativeEvent, event.currentTarget, '.nx-kanban-menu-choice', { orientation: 'vertical' })}
          >
            {card.actions?.map((action, i) => (
              <MenuItem key={i} action={action} onChoose={() => choose(action)} />
            ))}
            {card.actions && others.length > 0 && <hr className="nx-kanban-menu-sep" role="separator" />}
            {others.map((column) => (
              <button key={column.id} type="button" className="nx-kanban-menu-choice" role="menuitem" onClick={() => move(column.id)}>
                <Icon name="chevron-right" />
                <span>{moveTo(column.title)}</span>
              </button>
            ))}
          </div>
        </>
      )}
    </li>
  );
}

function MenuItem({ action, onChoose }: { action: KanbanCardAction; onChoose: () => void }) {
  const inner = (
    <>
      {action.icon && <Icon name={action.icon} />}
      <span>{action.label}</span>
    </>
  );
  return action.href ? (
    <SmartLink href={action.href} className="nx-kanban-menu-choice" role="menuitem" data-danger={action.danger ? '' : undefined} onClick={onChoose}>
      {inner}
    </SmartLink>
  ) : (
    <button type="button" className="nx-kanban-menu-choice" role="menuitem" data-danger={action.danger ? '' : undefined} onClick={onChoose}>
      {inner}
    </button>
  );
}

// apps/admin-vue/src/components/Kanban.vue
<script setup lang="ts">
/**
 * The kanban board — the hand-written Vue twin of the `kanban` block
 * (nx-kanban): native HTML5 drag & drop with the breathing placeholder pill at
 * the drop point, the FLIP glide after every reorder (core `snapshotRows` +
 * `playRowFlip`), the per-column quick-add composer and each card's three-dot
 * menu as a native popover (core `place` + `roveFocus`) holding the page's
 * actions and the "move to" items. The page owns the columns; reorders,
 * additions and menu picks come back up as events.
 */
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import {
  type Cleanup,
  type IconName,
  type RowSnapshot,
  place,
  playRowFlip,
  reveal,
  roveFocus,
  snapshotRows,
  translate,
} from '@nabuxai/ui-core';
import { lang, numberFmt } from '../store';
import NxIcon from './NxIcon.vue';

export type KanbanTone = 'accent' | 'success' | 'warning' | 'danger' | 'info' | 'gold';

export interface KanbanCardAction {
  id: string;
  label: string;
  icon?: IconName;
  danger?: boolean;
}

export interface KanbanCard {
  id: string;
  title: string;
  meta?: string;
  tone?: KanbanTone;
  assignee?: string;
}

export interface KanbanColumn {
  id: string;
  title: string;
  tone?: KanbanTone;
  cards: KanbanCard[];
}

export interface KanbanMove {
  card: string;
  from: string;
  to: string;
  index: number;
}

const props = withDefaults(
  defineProps<{
    columns: KanbanColumn[];
    label?: string;
    height?: string;
    addPlaceholder?: string;
    actions?: KanbanCardAction[];
  }>(),
  { label: undefined, height: undefined, addPlaceholder: undefined, actions: undefined },
);

const emit = defineEmits<{
  change: [columns: KanbanColumn[]];
  move: [move: KanbanMove];
  add: [payload: { column: string; title: string }];
  action: [payload: { id: string; cardId: string }];
}>();

const board = ref<HTMLElement | null>(null);
const dragging = ref<string | null>(null);
const over = ref<{ column: string; index: number } | null>(null);
const adding = ref<string | null>(null);
const announced = ref('');
let flight: RowSnapshot | null = null;
let stopReveal: (() => void) | null = null;

const cardsOf = () => board.value?.querySelectorAll<HTMLElement>('.nx-kanban-card[data-key]') ?? [];

onMounted(() => {
  if (board.value) stopReveal = reveal(board.value, { once: true });
});
onBeforeUnmount(() => stopReveal?.());

// After the page hands the new columns back, the cards glide to their places.
watch(
  () => props.columns,
  () => {
    if (!flight) return;
    const before = flight;
    flight = null;
    void nextTick(() => playRowFlip(cardsOf(), before));
  },
);

/** Where a pointer's Y falls in `list`: before which card (its index, or the end). */
function dropIndex(list: HTMLElement, y: number): number {
  const source = dragging.value ? board.value?.querySelector<HTMLElement>(`.nx-kanban-card[data-key="${CSS.escape(dragging.value)}"]`) ?? null : null;
  const cards = Array.from(list.querySelectorAll<HTMLElement>('.nx-kanban-card')).filter((card) => card !== source);
  for (let i = 0; i < cards.length; i++) {
    const rect = cards[i]!.getBoundingClientRect();
    if (y < rect.top + rect.height / 2) return i;
  }
  return cards.length;
}

// The interleaved render list: the placeholder sits among the column's *other*
// cards, so it shows where the dragged card will land once it leaves its slot.
interface Slot {
  key: string;
  card?: KanbanCard;
  index: number;
  placeholder?: boolean;
}

const slotsOf = (column: KanbanColumn): Slot[] => {
  const here = over.value?.column === column.id ? over.value.index : null;
  const items: Slot[] = [];
  let landing = 0;
  column.cards.forEach((card) => {
    if (card.id !== dragging.value) {
      if (here === landing) items.push({ key: `ph-${column.id}-${landing}`, index: landing, placeholder: true });
      landing += 1;
    }
    items.push({ key: card.id, card, index: landing });
  });
  if (here !== null && here >= landing) items.push({ key: `ph-${column.id}-end`, index: landing, placeholder: true });
  return items;
};

const commit = (move: KanbanMove) => {
  const next = props.columns.map((col) => ({ ...col, cards: [...col.cards] }));
  const from = next.find((col) => col.id === move.from);
  const to = next.find((col) => col.id === move.to);
  const card = from?.cards.find((c) => c.id === move.card);
  if (!from || !to || !card) return;
  flight = snapshotRows(cardsOf());
  from.cards = from.cards.filter((c) => c.id !== move.card);
  to.cards.splice(Math.max(0, Math.min(move.index, to.cards.length)), 0, card);
  emit('change', next);
  emit('move', move);
  const word = (key: 'kanbanMovedTo', params: Record<string, string>) => translate(lang.value, key, params);
  announced.value = word('kanbanMovedTo', { card: card.title, column: to.title });
};

/* ---- Native drag & drop ----------------------------------------------------------------- */

const onDragStart = (event: DragEvent, card: string) => {
  event.dataTransfer?.setData('text/plain', card);
  if (event.dataTransfer) event.dataTransfer.effectAllowed = 'move';
  dragging.value = card;
};

const onDragOver = (event: DragEvent, column: string) => {
  if (!dragging.value) return;
  event.preventDefault();
  if (event.dataTransfer) event.dataTransfer.dropEffect = 'move';
  const list = event.currentTarget as HTMLElement;
  const index = dropIndex(list, event.clientY);
  if (over.value?.column === column && over.value.index === index) return;
  over.value = { column, index };
};

const onDrop = (event: DragEvent, column: string) => {
  event.preventDefault();
  const card = dragging.value ?? event.dataTransfer?.getData('text/plain') ?? null;
  const from = props.columns.find((col) => col.cards.some((c) => c.id === card))?.id;
  dragging.value = null;
  over.value = null;
  if (!card || !from) return;
  const list = event.currentTarget as HTMLElement;
  commit({ card, from, to: column, index: dropIndex(list, event.clientY) });
};

const onDragLeave = (event: DragEvent, column: string) => {
  if ((event.currentTarget as HTMLElement).contains(event.relatedTarget as Node | null)) return;
  if (over.value?.column === column) over.value = null;
};

/* ---- Card menu: a native popover placed against its trigger ---------------------------- */

const openMenu = ref<string | null>(null);
const menuTriggers = new Map<string, HTMLButtonElement>();
const menuPanels = new Map<string, HTMLElement>();
const unplaces = new Map<string, Cleanup>();

function setMenuTrigger(cardId: string, el: unknown) {
  if (el) menuTriggers.set(cardId, el as HTMLButtonElement);
  else menuTriggers.delete(cardId);
}

function setMenuPanel(cardId: string, el: unknown) {
  if (el) menuPanels.set(cardId, el as HTMLElement);
  else menuPanels.delete(cardId);
}

onBeforeUnmount(() => {
  for (const stop of unplaces.values()) stop();
  unplaces.clear();
});

// The panel's own toggle event is the one source of truth (bound in the template).
function onMenuToggle(cardId: string, target: HTMLElement) {
  const shown = target.matches(':popover-open');
  openMenu.value = shown ? cardId : null;
  unplaces.get(cardId)?.();
  unplaces.delete(cardId);
  if (shown) {
    const trigger = menuTriggers.get(cardId);
    if (trigger) unplaces.set(cardId, place(trigger, target, { side: 'bottom', align: 'end', offset: 6 }));
  }
}

// An exit is softer and faster than the enter: fold away quickly.
const closeMenu = (cardId: string) =>
  window.setTimeout(() => {
    const panel = menuPanels.get(cardId);
    if (panel?.matches(':popover-open')) panel.hidePopover();
  }, 150);

const chooseAction = (action: KanbanCardAction, cardId: string) => {
  emit('action', { id: action.id, cardId });
  closeMenu(cardId);
};

const moveTo = (cardId: string, from: string, to: string) => {
  commit({ card: cardId, from, to, index: props.columns.find((col) => col.id === to)?.cards.length ?? 0 });
  closeMenu(cardId);
};

const othersOf = (cardId: string) => {
  const from = props.columns.find((col) => col.cards.some((c) => c.id === cardId))?.id;
  return props.columns.filter((col) => col.id !== from);
};

const onMenuKey = (event: KeyboardEvent) => {
  roveFocus(event, event.currentTarget as HTMLElement, '.nx-kanban-menu-choice', { orientation: 'vertical' });
};

/* ---- Quick add -------------------------------------------------------------------------- */

const submitAdd = (event: Event, column: string) => {
  const form = event.target as HTMLFormElement;
  const input = form.elements.namedItem('title') as HTMLInputElement | null;
  const title = input?.value.trim();
  if (!title) {
    input?.focus();
    return;
  }
  flight = snapshotRows(cardsOf());
  const next = props.columns.map((col) => (col.id === column ? { ...col, cards: [...col.cards, { id: `card-${Date.now().toString(36)}`, title }] } : col));
  emit('change', next);
  emit('add', { column, title });
  if (input) input.value = '';
  input?.focus();
};

const word = (key: 'kanbanBoard' | 'kanbanAddCard' | 'kanbanAdd' | 'kanbanEmpty' | 'kanbanCardMenu' | 'kanbanMoveTo' | 'kanbanCards', params: Record<string, string | number> = {}) =>
  translate(lang.value, key, params);

const hasMenu = (cardId: string) => (props.actions?.length ?? 0) > 0 || othersOf(cardId).length > 0;
</script>

<template>
  <section ref="board" class="nx-kanban" :aria-label="label ?? word('kanbanBoard')" :style="height ? { '--nx-kanban-height': height } : undefined">
    <div class="nx-kanban-board">
      <div
        v-for="column in columns"
        :key="column.id"
        class="nx-kanban-column"
        :data-column="column.id"
        :data-tone="column.tone"
        :data-dropping="over?.column === column.id ? '' : undefined"
      >
        <header class="nx-kanban-column-head">
          <span class="nx-kanban-column-dot" aria-hidden="true" />
          <h3 class="nx-kanban-column-title" :id="`nx-kanban-col-${column.id}`">{{ column.title }}</h3>
          <span class="nx-kanban-column-count" aria-hidden="true">{{ numberFmt.format(column.cards.length) }}</span>
          <span class="nx-visually-hidden">{{ word('kanbanCards', { count: numberFmt.format(column.cards.length) }) }}</span>
        </header>
        <ul
          class="nx-kanban-list"
          :aria-labelledby="`nx-kanban-col-${column.id}`"
          @dragover="(event) => onDragOver(event, column.id)"
          @drop="(event) => onDrop(event, column.id)"
          @dragleave="(event) => onDragLeave(event, column.id)"
        >
          <template v-for="slot in slotsOf(column)" :key="slot.key">
            <li v-if="slot.placeholder" class="nx-kanban-placeholder" aria-hidden="true">
              <span class="nx-kanban-placeholder-dot" />
              <span class="nx-kanban-placeholder-bar" />
            </li>
            <li
              v-else-if="slot.card"
              class="nx-kanban-card"
              :data-key="slot.card.id"
              :data-tone="slot.card.tone"
              :data-dragging="dragging === slot.card.id ? '' : undefined"
              :style="{ '--nx-i': slot.index }"
              draggable="true"
              @dragstart="(event) => onDragStart(event, slot.card!.id)"
              @dragend="dragging = null; over = null"
            >
              <span v-if="slot.card.tone" class="nx-kanban-card-dot" aria-hidden="true" />
              <div class="nx-kanban-card-main">
                <p class="nx-kanban-card-title">{{ slot.card.title }}</p>
                <p v-if="slot.card.meta" class="nx-kanban-card-meta">{{ slot.card.meta }}</p>
              </div>
              <span v-if="slot.card.assignee" class="nx-avatar" data-size="sm" role="img" :aria-label="slot.card.assignee">
                <span aria-hidden="true">{{ slot.card.assignee.split(/\s+/).slice(0, 2).map((p) => Array.from(p)[0]).join('').toLocaleUpperCase() }}</span>
              </span>
              <template v-if="hasMenu(slot.card.id)">
                <button
                  :ref="(el) => setMenuTrigger(slot.card!.id, el)"
                  type="button"
                  class="nx-kanban-card-menu"
                  aria-haspopup="menu"
                  :aria-expanded="openMenu === slot.card.id"
                  :aria-controls="`nx-kanban-menu-${slot.card.id}`"
                  :aria-label="word('kanbanCardMenu', { name: slot.card.title })"
                  :popovertarget="`nx-kanban-menu-${slot.card.id}`"
                >
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.75" stroke-linecap="round" aria-hidden="true">
                    <path d="M12 5.25h.01M12 12h.01M12 18.75h.01" />
                  </svg>
                </button>
                <div
                  :id="`nx-kanban-menu-${slot.card.id}`"
                  :ref="(el) => setMenuPanel(slot.card!.id, el)"
                  class="nx-kanban-menu"
                  role="menu"
                  :aria-label="word('kanbanCardMenu', { name: slot.card.title })"
                  popover="auto"
                  @toggle="onMenuToggle(slot.card!.id, $event.currentTarget as HTMLElement)"
                  @keydown="onMenuKey"
                >
                  <button
                    v-for="action in actions"
                    :key="action.id"
                    type="button"
                    class="nx-kanban-menu-choice"
                    role="menuitem"
                    :data-danger="action.danger ? '' : undefined"
                    @click="chooseAction(action, slot.card!.id)"
                  >
                    <NxIcon v-if="action.icon" :name="action.icon" />
                    <span>{{ action.label }}</span>
                  </button>
                  <hr v-if="actions && othersOf(slot.card.id).length > 0" class="nx-kanban-menu-sep" role="separator" />
                  <button
                    v-for="other in othersOf(slot.card.id)"
                    :key="other.id"
                    type="button"
                    class="nx-kanban-menu-choice"
                    role="menuitem"
                    @click="moveTo(slot.card!.id, column.id, other.id)"
                  >
                    <NxIcon name="chevron-right" />
                    <span>{{ word('kanbanMoveTo', { column: other.title }) }}</span>
                  </button>
                </div>
              </template>
            </li>
          </template>
          <li v-if="column.cards.length === 0 && over?.column !== column.id" class="nx-kanban-empty">{{ word('kanbanEmpty') }}</li>
        </ul>
        <div class="nx-kanban-add">
          <button
            type="button"
            class="nx-kanban-add-open"
            :aria-expanded="adding === column.id"
            :aria-controls="`nx-kanban-add-${column.id}`"
            @click="adding = adding === column.id ? null : column.id"
          >
            <NxIcon name="plus" />
            <span>{{ word('kanbanAddCard') }}</span>
          </button>
          <div class="nx-kanban-add-form" :id="`nx-kanban-add-${column.id}`" :data-open="adding === column.id ? '' : undefined">
            <form class="nx-kanban-add-body" @submit.prevent="(event) => submitAdd(event, column.id)">
              <input
                class="nx-kanban-add-input"
                name="title"
                type="text"
                autocomplete="off"
                :placeholder="addPlaceholder ?? word('kanbanAddCard')"
                :aria-label="word('kanbanAddCard')"
              />
              <button type="submit" class="nx-kanban-add-submit">{{ word('kanbanAdd') }}</button>
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- The move, spoken once it lands. -->
    <p class="nx-visually-hidden" role="status">{{ announced }}</p>
  </section>
</template>
